// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: autopay.sql

package sqlc

import (
	"context"
)

const getAutopayConfig = `-- name: GetAutopayConfig :one
SELECT enabled, threshold_usd_micros
FROM router.organization_autopay_config
WHERE organization_id = $1::varchar
`

type GetAutopayConfigRow struct {
	Enabled            bool
	ThresholdUsdMicros int64
}

// Returns the org's autopay configuration read by the router's debit hook to
// detect a balance crossing below the recharge threshold. A no-row result
// (the org never configured autopay) maps to a not-found error; the caller
// treats that as "autopay disabled" and skips the crossing check. Only the two
// columns the router needs are selected -- every other autopay column is
// written and read exclusively by the Weave control plane.
//
//	SELECT enabled, threshold_usd_micros
//	FROM router.organization_autopay_config
//	WHERE organization_id = $1::varchar
func (q *Queries) GetAutopayConfig(ctx context.Context, organizationID string) (GetAutopayConfigRow, error) {
	row := q.db.QueryRow(ctx, getAutopayConfig, organizationID)
	var i GetAutopayConfigRow
	err := row.Scan(&i.Enabled, &i.ThresholdUsdMicros)
	return i, err
}
