// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlc

import (
	"context"
)

const checkBillingTablesExist = `-- name: CheckBillingTablesExist :one
SELECT (
    SELECT COUNT(*) FROM information_schema.tables
    WHERE table_schema = 'router'
      AND table_name IN (
        'organization_credit_balance',
        'organization_credit_ledger',
        'organization_billing_overrides'
      )
) = 3 AS billing_tables_exist
`

// Returns true if the three billing tables exist in the router schema. Used
// by the router boot-time health check so a missing-migration state
// disables billing rather than 500ing on every request.
//
//	SELECT (
//	    SELECT COUNT(*) FROM information_schema.tables
//	    WHERE table_schema = 'router'
//	      AND table_name IN (
//	        'organization_credit_balance',
//	        'organization_credit_ledger',
//	        'organization_billing_overrides'
//	      )
//	) = 3 AS billing_tables_exist
func (q *Queries) CheckBillingTablesExist(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, checkBillingTablesExist)
	var billing_tables_exist bool
	err := row.Scan(&billing_tables_exist)
	return billing_tables_exist, err
}

const debitOrgCredits = `-- name: DebitOrgCredits :one
WITH updated AS (
    UPDATE router.organization_credit_balance
    SET balance_usd_micros = balance_usd_micros + $2::bigint,
        updated_at = NOW()
    WHERE organization_id = $1::varchar
    RETURNING balance_usd_micros
)
INSERT INTO router.organization_credit_ledger (
    organization_id,
    delta_usd_micros,
    notional_cost_micros,
    balance_after_micros,
    entry_type,
    router_request_id,
    router_model
)
SELECT
    $1::varchar,
    $2::bigint,
    $3::bigint,
    updated.balance_usd_micros,
    $4::varchar,
    $5::varchar,
    $6::varchar
FROM updated
RETURNING balance_after_micros
`

type DebitOrgCreditsParams struct {
	OrganizationID     string
	DeltaUsdMicros     int64
	NotionalCostMicros int64
	EntryType          string
	RouterRequestID    *string
	RouterModel        *string
}

// Atomic debit: decrement the balance and append a matching ledger row in a
// single statement. delta_usd_micros is the signed change (negative for an
// inference debit, zero for an override pass-through). notional_cost_micros
// is always the would-be charge, populated for both override and real
// debits so we keep a shadow billing trail.
//
// No `balance >= amount` guard: concurrent requests can both pass the
// preflight balance check and both debit; both debits must be recorded
// even if the resulting balance is briefly negative. The min-balance
// threshold on the middleware bounds the typical dip.
//
// Returns the post-debit balance so middleware/log lines can report the
// new value without a follow-up read.
//
//	WITH updated AS (
//	    UPDATE router.organization_credit_balance
//	    SET balance_usd_micros = balance_usd_micros + $2::bigint,
//	        updated_at = NOW()
//	    WHERE organization_id = $1::varchar
//	    RETURNING balance_usd_micros
//	)
//	INSERT INTO router.organization_credit_ledger (
//	    organization_id,
//	    delta_usd_micros,
//	    notional_cost_micros,
//	    balance_after_micros,
//	    entry_type,
//	    router_request_id,
//	    router_model
//	)
//	SELECT
//	    $1::varchar,
//	    $2::bigint,
//	    $3::bigint,
//	    updated.balance_usd_micros,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::varchar
//	FROM updated
//	RETURNING balance_after_micros
func (q *Queries) DebitOrgCredits(ctx context.Context, arg DebitOrgCreditsParams) (int64, error) {
	row := q.db.QueryRow(ctx, debitOrgCredits,
		arg.OrganizationID,
		arg.DeltaUsdMicros,
		arg.NotionalCostMicros,
		arg.EntryType,
		arg.RouterRequestID,
		arg.RouterModel,
	)
	var balance_after_micros int64
	err := row.Scan(&balance_after_micros)
	return balance_after_micros, err
}

const getActiveBillingOverride = `-- name: GetActiveBillingOverride :one
SELECT EXISTS (
    SELECT 1
    FROM router.organization_billing_overrides
    WHERE organization_id = $1::varchar
      AND (expires_at IS NULL OR expires_at > NOW())
)::boolean AS has_override
`

// Reports whether the org currently has an active billing override
// (free credits, internal account, enterprise trial). Returns the matching
// row id when present so callers can distinguish "no override" from a real
// failure path. Uses a one-shot existence query rather than fetching the
// override body — middleware only needs the boolean.
//
//	SELECT EXISTS (
//	    SELECT 1
//	    FROM router.organization_billing_overrides
//	    WHERE organization_id = $1::varchar
//	      AND (expires_at IS NULL OR expires_at > NOW())
//	)::boolean AS has_override
func (q *Queries) GetActiveBillingOverride(ctx context.Context, organizationID string) (bool, error) {
	row := q.db.QueryRow(ctx, getActiveBillingOverride, organizationID)
	var has_override bool
	err := row.Scan(&has_override)
	return has_override, err
}

const getOrgCreditBalance = `-- name: GetOrgCreditBalance :one
SELECT balance_usd_micros
FROM router.organization_credit_balance
WHERE organization_id = $1::varchar
`

// Returns the org's current prepaid balance in USD micros. NULL is mapped to
// a no-row error so callers can detect missing balance rows and decide
// explicitly whether 0 or "no row" is the right answer (the middleware
// treats both as a 402 candidate).
//
//	SELECT balance_usd_micros
//	FROM router.organization_credit_balance
//	WHERE organization_id = $1::varchar
func (q *Queries) GetOrgCreditBalance(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, getOrgCreditBalance, organizationID)
	var balance_usd_micros int64
	err := row.Scan(&balance_usd_micros)
	return balance_usd_micros, err
}

const listOrgLedger = `-- name: ListOrgLedger :many
SELECT
    id,
    organization_id,
    delta_usd_micros,
    notional_cost_micros,
    balance_after_micros,
    entry_type,
    stripe_payment_intent_id,
    router_request_id,
    router_model,
    created_at
FROM router.organization_credit_ledger
WHERE organization_id = $1::varchar
ORDER BY created_at DESC
LIMIT $2::int
`

type ListOrgLedgerParams struct {
	OrganizationID string
	RowLimit       int32
}

// Paginated read for the dashboard ledger panel. Sorted newest-first so the
// UI can render without an extra ORDER BY in Go.
//
//	SELECT
//	    id,
//	    organization_id,
//	    delta_usd_micros,
//	    notional_cost_micros,
//	    balance_after_micros,
//	    entry_type,
//	    stripe_payment_intent_id,
//	    router_request_id,
//	    router_model,
//	    created_at
//	FROM router.organization_credit_ledger
//	WHERE organization_id = $1::varchar
//	ORDER BY created_at DESC
//	LIMIT $2::int
func (q *Queries) ListOrgLedger(ctx context.Context, arg ListOrgLedgerParams) ([]RouterOrganizationCreditLedger, error) {
	rows, err := q.db.Query(ctx, listOrgLedger, arg.OrganizationID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterOrganizationCreditLedger
	for rows.Next() {
		var i RouterOrganizationCreditLedger
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DeltaUsdMicros,
			&i.NotionalCostMicros,
			&i.BalanceAfterMicros,
			&i.EntryType,
			&i.StripePaymentIntentID,
			&i.RouterRequestID,
			&i.RouterModel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
