// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cluster_model_lists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getClusterModelListsByAPIKey = `-- name: GetClusterModelListsByAPIKey :many
SELECT id, organization_id, api_key_id, cluster_label, models, created_at, updated_at
FROM router.cluster_model_lists
WHERE api_key_id = $1::uuid
ORDER BY cluster_label
`

// Returns all cluster allowlists for a given API key. Writes are owned by the
// Weave control plane (direct inserts to this schema, mirroring
// excluded_models / preferred_models); the router only reads on the auth path.
//
//	SELECT id, organization_id, api_key_id, cluster_label, models, created_at, updated_at
//	FROM router.cluster_model_lists
//	WHERE api_key_id = $1::uuid
//	ORDER BY cluster_label
func (q *Queries) GetClusterModelListsByAPIKey(ctx context.Context, apiKeyID uuid.UUID) ([]RouterClusterModelList, error) {
	rows, err := q.db.Query(ctx, getClusterModelListsByAPIKey, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterClusterModelList
	for rows.Next() {
		var i RouterClusterModelList
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.APIKeyID,
			&i.ClusterLabel,
			&i.Models,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
