// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loop_escalation_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countLoopEscalationEvents = `-- name: CountLoopEscalationEvents :one
SELECT COUNT(*)
FROM router.loop_escalation_events
WHERE session_key = $1::bytea
  AND role        = $2::varchar
`

type CountLoopEscalationEventsParams struct {
	SessionKey []byte
	Role       string
}

// Once-per-session budget check: any prior event for this (session, role)
// means the detector already fired and must not fire again, even after the
// session pin's TTL expires.
//
//	SELECT COUNT(*)
//	FROM router.loop_escalation_events
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
func (q *Queries) CountLoopEscalationEvents(ctx context.Context, arg CountLoopEscalationEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoopEscalationEvents, arg.SessionKey, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertLoopEscalationEvent = `-- name: InsertLoopEscalationEvent :exec
INSERT INTO router.loop_escalation_events (
    installation_id,
    session_key,
    role,
    looping_model,
    action,
    escalation_target,
    loop_tool,
    loop_input_hash,
    repeat_count,
    distinct_ratio,
    window_size
) VALUES (
    $1::uuid,
    $2::bytea,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::varchar,
    $8::varchar,
    $9::int,
    $10::double precision,
    $11::int
)
`

type InsertLoopEscalationEventParams struct {
	InstallationID   uuid.UUID
	SessionKey       []byte
	Role             string
	LoopingModel     string
	Action           string
	EscalationTarget string
	LoopTool         string
	LoopInputHash    string
	RepeatCount      int32
	DistinctRatio    float64
	WindowSize       int32
}

// Records one cyclic-loop detection. Written at detection time with
// context.Background() (the request ctx may already be canceled); the
// post-escalation outcome is joined offline by session_key against
// model_router_request_telemetry / session results.
//
//	INSERT INTO router.loop_escalation_events (
//	    installation_id,
//	    session_key,
//	    role,
//	    looping_model,
//	    action,
//	    escalation_target,
//	    loop_tool,
//	    loop_input_hash,
//	    repeat_count,
//	    distinct_ratio,
//	    window_size
//	) VALUES (
//	    $1::uuid,
//	    $2::bytea,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::varchar,
//	    $7::varchar,
//	    $8::varchar,
//	    $9::int,
//	    $10::double precision,
//	    $11::int
//	)
func (q *Queries) InsertLoopEscalationEvent(ctx context.Context, arg InsertLoopEscalationEventParams) error {
	_, err := q.db.Exec(ctx, insertLoopEscalationEvent,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.LoopingModel,
		arg.Action,
		arg.EscalationTarget,
		arg.LoopTool,
		arg.LoopInputHash,
		arg.RepeatCount,
		arg.DistinctRatio,
		arg.WindowSize,
	)
	return err
}
