// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_api_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createModelRouterAPIKey = `-- name: CreateModelRouterAPIKey :one
INSERT INTO router.model_router_api_keys (
    installation_id,
    external_id,
    name,
    key_prefix,
    key_hash,
    key_suffix,
    created_by
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7
)
RETURNING id, installation_id, external_id, name, key_prefix, key_hash, key_suffix, last_used_at, created_at, deleted_at, created_by
`

type CreateModelRouterAPIKeyParams struct {
	InstallationID uuid.UUID
	ExternalID     string
	Name           *string
	KeyPrefix      string
	KeyHash        string
	KeySuffix      string
	CreatedBy      *string
}

// Creates a new model router API key bound to an installation.
//
//	INSERT INTO router.model_router_api_keys (
//	    installation_id,
//	    external_id,
//	    name,
//	    key_prefix,
//	    key_hash,
//	    key_suffix,
//	    created_by
//	)
//	VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::varchar,
//	    $7
//	)
//	RETURNING id, installation_id, external_id, name, key_prefix, key_hash, key_suffix, last_used_at, created_at, deleted_at, created_by
func (q *Queries) CreateModelRouterAPIKey(ctx context.Context, arg CreateModelRouterAPIKeyParams) (RouterModelRouterAPIKey, error) {
	row := q.db.QueryRow(ctx, createModelRouterAPIKey,
		arg.InstallationID,
		arg.ExternalID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.KeySuffix,
		arg.CreatedBy,
	)
	var i RouterModelRouterAPIKey
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExternalID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeySuffix,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getActiveModelRouterAPIKeyWithInstallationByHash = `-- name: GetActiveModelRouterAPIKeyWithInstallationByHash :one
SELECT k.id, k.installation_id, k.external_id, k.name, k.key_prefix, k.key_hash, k.key_suffix, k.last_used_at, k.created_at, k.deleted_at, k.created_by, i.id, i.external_id, i.name, i.created_at, i.updated_at, i.deleted_at, i.created_by, i.is_eval_allowlisted
FROM router.model_router_api_keys k
INNER JOIN router.model_router_installations i ON i.id = k.installation_id
WHERE k.key_hash = $1::varchar
  AND k.deleted_at IS NULL
  AND i.deleted_at IS NULL
`

type GetActiveModelRouterAPIKeyWithInstallationByHashRow struct {
	RouterModelRouterAPIKey       RouterModelRouterAPIKey
	RouterModelRouterInstallation RouterModelRouterInstallation
}

// Hot-path auth lookup. Matches a token's SHA-256 hash to an active api key plus its
// active installation in a single indexed JOIN. Returns sql.ErrNoRows when nothing
// matches; the auth middleware maps that to a 401. Filters out soft-deleted rows on
// both sides so a soft-deleted installation invalidates all its keys without per-key
// updates.
//
//	SELECT k.id, k.installation_id, k.external_id, k.name, k.key_prefix, k.key_hash, k.key_suffix, k.last_used_at, k.created_at, k.deleted_at, k.created_by, i.id, i.external_id, i.name, i.created_at, i.updated_at, i.deleted_at, i.created_by, i.is_eval_allowlisted
//	FROM router.model_router_api_keys k
//	INNER JOIN router.model_router_installations i ON i.id = k.installation_id
//	WHERE k.key_hash = $1::varchar
//	  AND k.deleted_at IS NULL
//	  AND i.deleted_at IS NULL
func (q *Queries) GetActiveModelRouterAPIKeyWithInstallationByHash(ctx context.Context, keyHash string) (GetActiveModelRouterAPIKeyWithInstallationByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveModelRouterAPIKeyWithInstallationByHash, keyHash)
	var i GetActiveModelRouterAPIKeyWithInstallationByHashRow
	err := row.Scan(
		&i.RouterModelRouterAPIKey.ID,
		&i.RouterModelRouterAPIKey.InstallationID,
		&i.RouterModelRouterAPIKey.ExternalID,
		&i.RouterModelRouterAPIKey.Name,
		&i.RouterModelRouterAPIKey.KeyPrefix,
		&i.RouterModelRouterAPIKey.KeyHash,
		&i.RouterModelRouterAPIKey.KeySuffix,
		&i.RouterModelRouterAPIKey.LastUsedAt,
		&i.RouterModelRouterAPIKey.CreatedAt,
		&i.RouterModelRouterAPIKey.DeletedAt,
		&i.RouterModelRouterAPIKey.CreatedBy,
		&i.RouterModelRouterInstallation.ID,
		&i.RouterModelRouterInstallation.ExternalID,
		&i.RouterModelRouterInstallation.Name,
		&i.RouterModelRouterInstallation.CreatedAt,
		&i.RouterModelRouterInstallation.UpdatedAt,
		&i.RouterModelRouterInstallation.DeletedAt,
		&i.RouterModelRouterInstallation.CreatedBy,
		&i.RouterModelRouterInstallation.IsEvalAllowlisted,
	)
	return i, err
}

const listModelRouterAPIKeysForInstallation = `-- name: ListModelRouterAPIKeysForInstallation :many
SELECT id, installation_id, external_id, name, key_prefix, key_hash, key_suffix, last_used_at, created_at, deleted_at, created_by
FROM router.model_router_api_keys
WHERE installation_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Lists active keys for an installation (dashboard / CRUD; not on the request path).
//
//	SELECT id, installation_id, external_id, name, key_prefix, key_hash, key_suffix, last_used_at, created_at, deleted_at, created_by
//	FROM router.model_router_api_keys
//	WHERE installation_id = $1::uuid
//	  AND deleted_at IS NULL
//	ORDER BY created_at DESC
func (q *Queries) ListModelRouterAPIKeysForInstallation(ctx context.Context, installationID uuid.UUID) ([]RouterModelRouterAPIKey, error) {
	rows, err := q.db.Query(ctx, listModelRouterAPIKeysForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterAPIKey
	for rows.Next() {
		var i RouterModelRouterAPIKey
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.ExternalID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.KeySuffix,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelRouterAPIKeyUsed = `-- name: MarkModelRouterAPIKeyUsed :exec
UPDATE router.model_router_api_keys
SET last_used_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Records that a key was used. Called fire-and-forget by the Service after successful
// auth. Idempotent on retry.
//
//	UPDATE router.model_router_api_keys
//	SET last_used_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) MarkModelRouterAPIKeyUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markModelRouterAPIKeyUsed, id)
	return err
}

const softDeleteModelRouterAPIKey = `-- name: SoftDeleteModelRouterAPIKey :exec
UPDATE router.model_router_api_keys
SET deleted_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Soft-deletes a key.
//
//	UPDATE router.model_router_api_keys
//	SET deleted_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteModelRouterAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteModelRouterAPIKey, id)
	return err
}
