// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getModelRouterUser = `-- name: GetModelRouterUser :one
SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
FROM router.model_router_users
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Single-row read by id; returns sql.ErrNoRows when missing or soft-deleted.
//
//	SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
//	FROM router.model_router_users
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) GetModelRouterUser(ctx context.Context, id uuid.UUID) (RouterModelRouterUser, error) {
	row := q.db.QueryRow(ctx, getModelRouterUser, id)
	var i RouterModelRouterUser
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Email,
		&i.ClaudeAccountUUID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.DisplayName,
	)
	return i, err
}

const listModelRouterUsersForInstallation = `-- name: ListModelRouterUsersForInstallation :many
SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
FROM router.model_router_users
WHERE installation_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY last_seen_at DESC
`

// Lists active users for an installation (admin / dashboard; not on the request path).
//
//	SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
//	FROM router.model_router_users
//	WHERE installation_id = $1::uuid
//	  AND deleted_at IS NULL
//	ORDER BY last_seen_at DESC
func (q *Queries) ListModelRouterUsersForInstallation(ctx context.Context, installationID uuid.UUID) ([]RouterModelRouterUser, error) {
	rows, err := q.db.Query(ctx, listModelRouterUsersForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterUser
	for rows.Next() {
		var i RouterModelRouterUser
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Email,
			&i.ClaudeAccountUUID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.DeletedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelRouterUserByAccountUUID = `-- name: UpsertModelRouterUserByAccountUUID :one
INSERT INTO router.model_router_users (
    installation_id,
    email,
    claude_account_uuid,
    display_name
)
VALUES (
    $1::uuid,
    NULL,
    $2::uuid,
    $3::text
)
ON CONFLICT (installation_id, claude_account_uuid)
  WHERE email IS NULL AND claude_account_uuid IS NOT NULL AND deleted_at IS NULL
DO UPDATE SET
    last_seen_at = CURRENT_TIMESTAMP,
    display_name = COALESCE(EXCLUDED.display_name, router.model_router_users.display_name)
RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
`

type UpsertModelRouterUserByAccountUUIDParams struct {
	InstallationID    uuid.UUID
	ClaudeAccountUUID uuid.UUID
	DisplayName       *string
}

// Upserts an end-user identity keyed on (installation_id, claude_account_uuid)
// for inbound requests that carry no email. Claude CLI v2.1.x ships only
// {device_id, account_uuid, session_id} in metadata.user_id, so the
// email-keyed upsert above would silently drop attribution for every such
// request. The CONFLICT target matches the partial unique index
// model_router_users_installation_account_unique
// (WHERE email IS NULL AND claude_account_uuid IS NOT NULL).
//
//	INSERT INTO router.model_router_users (
//	    installation_id,
//	    email,
//	    claude_account_uuid,
//	    display_name
//	)
//	VALUES (
//	    $1::uuid,
//	    NULL,
//	    $2::uuid,
//	    $3::text
//	)
//	ON CONFLICT (installation_id, claude_account_uuid)
//	  WHERE email IS NULL AND claude_account_uuid IS NOT NULL AND deleted_at IS NULL
//	DO UPDATE SET
//	    last_seen_at = CURRENT_TIMESTAMP,
//	    display_name = COALESCE(EXCLUDED.display_name, router.model_router_users.display_name)
//	RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
func (q *Queries) UpsertModelRouterUserByAccountUUID(ctx context.Context, arg UpsertModelRouterUserByAccountUUIDParams) (RouterModelRouterUser, error) {
	row := q.db.QueryRow(ctx, upsertModelRouterUserByAccountUUID, arg.InstallationID, arg.ClaudeAccountUUID, arg.DisplayName)
	var i RouterModelRouterUser
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Email,
		&i.ClaudeAccountUUID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.DisplayName,
	)
	return i, err
}

const upsertModelRouterUserByEmail = `-- name: UpsertModelRouterUserByEmail :one
WITH merged AS (
    UPDATE router.model_router_users
    SET email        = $1::text,
        display_name = COALESCE($2::text, display_name),
        last_seen_at = CURRENT_TIMESTAMP
    WHERE installation_id     = $3::uuid
      AND claude_account_uuid = $4::uuid
      AND email IS NULL
      AND deleted_at IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM router.model_router_users
          WHERE installation_id = $3::uuid
            AND email = $1::text
            AND deleted_at IS NULL
      )
    RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
),
inserted AS (
    INSERT INTO router.model_router_users (
        installation_id,
        email,
        claude_account_uuid,
        display_name
    )
    SELECT
        $3::uuid,
        $1::text,
        $4::uuid,
        $2::text
    WHERE NOT EXISTS (SELECT 1 FROM merged)
    ON CONFLICT (installation_id, email) WHERE deleted_at IS NULL DO UPDATE SET
        last_seen_at        = CURRENT_TIMESTAMP,
        claude_account_uuid = COALESCE(EXCLUDED.claude_account_uuid, router.model_router_users.claude_account_uuid),
        display_name        = COALESCE(EXCLUDED.display_name, router.model_router_users.display_name)
    RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
)
SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name FROM merged
UNION ALL
SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name FROM inserted
`

type UpsertModelRouterUserByEmailParams struct {
	Email             string
	DisplayName       *string
	InstallationID    uuid.UUID
	ClaudeAccountUUID pgtype.UUID
}

type UpsertModelRouterUserByEmailRow struct {
	ID                uuid.UUID
	InstallationID    uuid.UUID
	Email             *string
	ClaudeAccountUUID pgtype.UUID
	FirstSeenAt       pgtype.Timestamp
	LastSeenAt        pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
	DisplayName       *string
}

// Upserts an end-user identity keyed on (installation_id, email), refreshing
// last_seen_at on every hit. claude_account_uuid and display_name are
// overwritten only when the new value is non-NULL so a request from a
// non-Claude-Code client (or one that omits the X-Weave-User-Name header)
// can't blank out fields populated by earlier requests. Returns the row so
// the caller can stash user_id on the request context.
//
// Merge path: when claude_account_uuid is non-NULL and a UUID-only orphan
// already exists for this account (created by an earlier email-less request
// via UpsertModelRouterUserByAccountUUID), we update that row's email +
// display_name in place instead of inserting a new email-keyed row. Without
// this, every installer upgrade that introduces X-Weave-User-Email creates
// duplicate rows for the same human and the dashboard picker shows both.
// The fallback INSERT keeps the original ON CONFLICT path so concurrent
// email-bearing requests still collapse onto a single row.
//
// Merge is gated on the absence of an existing email-keyed row for the same
// (installation_id, email): if one already exists (created by an earlier
// email-bearing request that didn't carry account_uuid), the orphan UPDATE
// would collide with the partial unique index
// model_router_users_installation_email_unique and fail the whole upsert
// with SQLSTATE 23505. In that case we let the INSERT path take over so the
// existing email-keyed row gets its claude_account_uuid backfilled via the
// ON CONFLICT DO UPDATE clause; the orphan stays in place (dashboard surfaces
// the email-keyed row, which is the canonical identity).
//
//	WITH merged AS (
//	    UPDATE router.model_router_users
//	    SET email        = $1::text,
//	        display_name = COALESCE($2::text, display_name),
//	        last_seen_at = CURRENT_TIMESTAMP
//	    WHERE installation_id     = $3::uuid
//	      AND claude_account_uuid = $4::uuid
//	      AND email IS NULL
//	      AND deleted_at IS NULL
//	      AND NOT EXISTS (
//	          SELECT 1 FROM router.model_router_users
//	          WHERE installation_id = $3::uuid
//	            AND email = $1::text
//	            AND deleted_at IS NULL
//	      )
//	    RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
//	),
//	inserted AS (
//	    INSERT INTO router.model_router_users (
//	        installation_id,
//	        email,
//	        claude_account_uuid,
//	        display_name
//	    )
//	    SELECT
//	        $3::uuid,
//	        $1::text,
//	        $4::uuid,
//	        $2::text
//	    WHERE NOT EXISTS (SELECT 1 FROM merged)
//	    ON CONFLICT (installation_id, email) WHERE deleted_at IS NULL DO UPDATE SET
//	        last_seen_at        = CURRENT_TIMESTAMP,
//	        claude_account_uuid = COALESCE(EXCLUDED.claude_account_uuid, router.model_router_users.claude_account_uuid),
//	        display_name        = COALESCE(EXCLUDED.display_name, router.model_router_users.display_name)
//	    RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name
//	)
//	SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name FROM merged
//	UNION ALL
//	SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at, display_name FROM inserted
func (q *Queries) UpsertModelRouterUserByEmail(ctx context.Context, arg UpsertModelRouterUserByEmailParams) (UpsertModelRouterUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertModelRouterUserByEmail,
		arg.Email,
		arg.DisplayName,
		arg.InstallationID,
		arg.ClaudeAccountUUID,
	)
	var i UpsertModelRouterUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Email,
		&i.ClaudeAccountUUID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.DisplayName,
	)
	return i, err
}
