// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_external_api_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createExternalAPIKey = `-- name: CreateExternalAPIKey :one
INSERT INTO router.model_router_external_api_keys (
    installation_id,
    external_id,
    provider,
    key_ciphertext,
    key_prefix,
    key_suffix,
    key_fingerprint,
    name,
    created_by
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::bytea,
    $5::varchar,
    $6::varchar,
    $7::varchar,
    $8,
    $9
)
RETURNING id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by
`

type CreateExternalAPIKeyParams struct {
	InstallationID uuid.UUID
	ExternalID     string
	Provider       string
	KeyCiphertext  []byte
	KeyPrefix      string
	KeySuffix      string
	KeyFingerprint string
	Name           *string
	CreatedBy      *string
}

// Creates a new external API key for an installation. The unique index on
// (installation_id, provider) WHERE deleted_at IS NULL enforces one key per
// provider; callers must soft-delete the existing key before inserting.
//
//	INSERT INTO router.model_router_external_api_keys (
//	    installation_id,
//	    external_id,
//	    provider,
//	    key_ciphertext,
//	    key_prefix,
//	    key_suffix,
//	    key_fingerprint,
//	    name,
//	    created_by
//	)
//	VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::bytea,
//	    $5::varchar,
//	    $6::varchar,
//	    $7::varchar,
//	    $8,
//	    $9
//	)
//	RETURNING id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by
func (q *Queries) CreateExternalAPIKey(ctx context.Context, arg CreateExternalAPIKeyParams) (RouterModelRouterExternalAPIKey, error) {
	row := q.db.QueryRow(ctx, createExternalAPIKey,
		arg.InstallationID,
		arg.ExternalID,
		arg.Provider,
		arg.KeyCiphertext,
		arg.KeyPrefix,
		arg.KeySuffix,
		arg.KeyFingerprint,
		arg.Name,
		arg.CreatedBy,
	)
	var i RouterModelRouterExternalAPIKey
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExternalID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.KeyFingerprint,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getActiveExternalAPIKeysForInstallation = `-- name: GetActiveExternalAPIKeysForInstallation :many
SELECT id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by
FROM router.model_router_external_api_keys
WHERE installation_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY provider, created_at DESC
`

// Returns all active external API keys for an installation. Used by the auth
// cache to populate the ExternalKeys map on cache miss.
//
//	SELECT id, installation_id, external_id, provider, key_ciphertext, key_prefix, key_suffix, key_fingerprint, name, last_used_at, created_at, updated_at, deleted_at, created_by
//	FROM router.model_router_external_api_keys
//	WHERE installation_id = $1::uuid
//	  AND deleted_at IS NULL
//	ORDER BY provider, created_at DESC
func (q *Queries) GetActiveExternalAPIKeysForInstallation(ctx context.Context, installationID uuid.UUID) ([]RouterModelRouterExternalAPIKey, error) {
	rows, err := q.db.Query(ctx, getActiveExternalAPIKeysForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterExternalAPIKey
	for rows.Next() {
		var i RouterModelRouterExternalAPIKey
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.ExternalID,
			&i.Provider,
			&i.KeyCiphertext,
			&i.KeyPrefix,
			&i.KeySuffix,
			&i.KeyFingerprint,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExternalAPIKeyUsed = `-- name: MarkExternalAPIKeyUsed :exec
UPDATE router.model_router_external_api_keys
SET last_used_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Fire-and-forget update after successful upstream call.
//
//	UPDATE router.model_router_external_api_keys
//	SET last_used_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) MarkExternalAPIKeyUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markExternalAPIKeyUsed, id)
	return err
}

const softDeleteExternalAPIKey = `-- name: SoftDeleteExternalAPIKey :exec
UPDATE router.model_router_external_api_keys
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1::uuid
  AND installation_id = $2::uuid
  AND deleted_at IS NULL
`

type SoftDeleteExternalAPIKeyParams struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
}

// Soft-deletes an external API key. Cross-tenant safe via installation_id predicate.
//
//	UPDATE router.model_router_external_api_keys
//	SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1::uuid
//	  AND installation_id = $2::uuid
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteExternalAPIKey(ctx context.Context, arg SoftDeleteExternalAPIKeyParams) error {
	_, err := q.db.Exec(ctx, softDeleteExternalAPIKey, arg.ID, arg.InstallationID)
	return err
}

const softDeleteExternalAPIKeyByProvider = `-- name: SoftDeleteExternalAPIKeyByProvider :exec
UPDATE router.model_router_external_api_keys
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE installation_id = $1::uuid
  AND provider = $2::varchar
  AND deleted_at IS NULL
`

type SoftDeleteExternalAPIKeyByProviderParams struct {
	InstallationID uuid.UUID
	Provider       string
}

// Soft-deletes the existing key for a provider before upsert.
//
//	UPDATE router.model_router_external_api_keys
//	SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
//	WHERE installation_id = $1::uuid
//	  AND provider = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteExternalAPIKeyByProvider(ctx context.Context, arg SoftDeleteExternalAPIKeyByProviderParams) error {
	_, err := q.db.Exec(ctx, softDeleteExternalAPIKeyByProvider, arg.InstallationID, arg.Provider)
	return err
}
