// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Cyclic tool-call loop detections: ops signal and (session, looping_model) -> looped training labels
type RouterLoopEscalationEvent struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	InstallationID uuid.UUID
	// 16-byte digest matching router.session_pins.session_key; join key for post-escalation outcome
	SessionKey       []byte
	Role             string
	LoopingModel     string
	Action           string
	EscalationTarget string
	LoopTool         string
	LoopInputHash    string
	RepeatCount      int32
	DistinctRatio    float64
	WindowSize       int32
}

// Rotatable bearer keys (rk_ prefix). An installation may hold multiple active keys; identity is carried by router.model_router_users.
type RouterModelRouterAPIKey struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	ExternalID     string
	Name           *string
	KeyPrefix      string
	// SHA-256 of the full rk_ token
	KeyHash string
	// Last 4 chars for display
	KeySuffix  string
	LastUsedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
	CreatedBy  *string
}

// Customer-owned provider API keys for BYOK routing
type RouterModelRouterExternalAPIKey struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	ExternalID     string
	Provider       string
	// AES-256-GCM encrypted API key with 12-byte nonce prepended
	KeyCiphertext []byte
	KeyPrefix     string
	KeySuffix     string
	// SHA-256 of plaintext for deduplication display
	KeyFingerprint string
	Name           *string
	LastUsedAt     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	CreatedBy      *string
}

// Customer router installations; owns API keys
type RouterModelRouterInstallation struct {
	ID                uuid.UUID
	ExternalID        string
	Name              string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
	CreatedBy         *string
	ExcludedModels    []string
	ExcludedProviders []string
}

type RouterModelRouterRequestTelemetry struct {
	ID                     uuid.UUID
	InstallationID         uuid.UUID
	RequestID              string
	SpanType               string
	TraceID                string
	Timestamp              pgtype.Timestamptz
	RequestedModel         *string
	DecisionModel          *string
	DecisionProvider       *string
	DecisionReason         *string
	EstimatedInputTokens   *int32
	StickyHit              *bool
	EmbedInput             *string
	InputTokens            *int32
	OutputTokens           *int32
	RequestedInputCostUsd  *int64
	RequestedOutputCostUsd *int64
	ActualInputCostUsd     *int64
	ActualOutputCostUsd    *int64
	RouteLatencyMs         *int64
	UpstreamLatencyMs      *int64
	TotalLatencyMs         *int64
	CrossFormat            *bool
	UpstreamStatusCode     *int32
	CreatedAt              pgtype.Timestamptz
	ClusterIds             []int32
	CandidateModels        []string
	ChosenScore            *float64
	AlphaBreakdown         []byte
	ClusterRouterVersion   *string
	TtftMs                 *int64
	CacheCreationTokens    *int32
	CacheReadTokens        *int32
	DeviceID               *string
	SessionID              *string
	CandidateScores        []byte
	Propensity             *float64
	RouterUserID           pgtype.UUID
	ClientApp              *string
	TurnType               *string
	RolloutID              *string
	// Copied from session_pins.trajectory_id at decision time; the offline trajectory join key
	TrajectoryID pgtype.UUID
	// Atomic per-trajectory turn counter (pins row), not timestamp ordering
	TurnIdx *int32
	// Versioned observation record computed in the Go hot path; trainers consume it verbatim and never reconstruct features
	StepRecord []byte
	// Schema version of step_record; trainers refuse mixed versions without a migration map
	StepRecordVersion *int32
	// Behavior policy distribution over eligible models {model: probability}; NULL on non-policy spans
	ActionDistribution []byte
	// Eligible set after provider/exclusion/capability/context filters, at decision time
	EligibleModels []string
	// Set when a safety override (hard pin, force-model, error failover) bypassed the policy; row excluded from policy training
	OverrideReason *string
}

// End-user identities seen on inbound requests, scoped to an installation. Replaces the per-user API key pattern.
type RouterModelRouterUser struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	// Lowercased, trimmed user email (typically git user.email). Nullable: Claude CLI versions that send only account_uuid in metadata.user_id produce email-NULL rows keyed on (installation_id, claude_account_uuid).
	Email *string
	// Optional Claude Code account_uuid carried in metadata.user_id; informational only.
	ClaudeAccountUUID pgtype.UUID
	FirstSeenAt       pgtype.Timestamp
	LastSeenAt        pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
	// Free-form user display name (typically git user.name) carried on the X-Weave-User-Name request header. Nullable: requests without the header leave the column NULL; existing rows are not back-filled.
	DisplayName *string
}

type RouterOrganizationBillingOverride struct {
	OrganizationID string
	Reason         string
	ExpiresAt      pgtype.Timestamptz
	CreatedBy      *string
	CreatedAt      pgtype.Timestamptz
}

type RouterOrganizationCreditBalance struct {
	OrganizationID   string
	BalanceUsdMicros int64
	UpdatedAt        pgtype.Timestamptz
}

type RouterOrganizationCreditLedger struct {
	ID                    uuid.UUID
	OrganizationID        string
	DeltaUsdMicros        int64
	NotionalCostMicros    int64
	BalanceAfterMicros    int64
	EntryType             string
	StripePaymentIntentID *string
	RouterRequestID       *string
	RouterModel           *string
	CreatedAt             pgtype.Timestamptz
	Memo                  *string
}

// Session-sticky routing pins; sliding 1h TTL matching Anthropic prompt cache
type RouterSessionPin struct {
	// 16-byte digest derived from api_key_id + (metadata.user_id | system+first-user hashes)
	SessionKey []byte
	// Stage 1 always emits "default"; turn-type roles land with §3.3
	Role                      string
	InstallationID            uuid.UUID
	PinnedProvider            string
	PinnedModel               string
	DecisionReason            string
	TurnCount                 int32
	PinnedUntil               pgtype.Timestamp
	FirstPinnedAt             pgtype.Timestamp
	LastSeenAt                pgtype.Timestamp
	LastInputTokens           int32
	LastCachedReadTokens      int32
	LastCachedWriteTokens     int32
	LastOutputTokens          int32
	LastTurnEndedAt           pgtype.Timestamptz
	ConsecutiveUpstreamErrors int32
	LastServedModel           string
	HasEverSwitched           bool
	// Stable trajectory UUID minted on first pin; survives session-key drift, copied onto telemetry rows
	TrajectoryID uuid.UUID
	// Trajectory of the dispatching parent session for sub-agent threads; NULL for main loops
	ParentTrajectoryID pgtype.UUID
	// LRU map keyed "provider/model" -> {last_turn_at, last_input_tokens, last_cache_read_tokens, last_cache_creation_tokens, last_output_tokens, consecutive_turns, last_reconcile_error_tokens}
	CacheLedger []byte
	// Running actual upstream spend for the session in micro-USD, accumulated on usage writeback
	CumulativeSpendMicrousd int64
	// Number of served-model switches observed on usage writeback (complements has_ever_switched latch)
	SwitchCount int32
}

// Shadow-mode spiral (death-march) detections: log-only fire-rate corpus measured on live traffic before escalation is armed
type RouterSpiralShadowEvent struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	InstallationID uuid.UUID
	// 16-byte digest matching router.session_pins.session_key; join key for session outcome
	SessionKey       []byte
	Role             string
	RoutedModel      string
	TurnType         string
	Reason           string
	ErrStreak        int32
	ErroredResults   int32
	ToolResults      int32
	MaxSameFileEdits int32
	SameFilePathHash string
	RepeatFrac       float64
	MonologueLen     int32
	ToolCallCount    int32
	MessageCount     int32
}
