// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_installations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createModelRouterInstallation = `-- name: CreateModelRouterInstallation :one
INSERT INTO router.model_router_installations (
    external_id,
    name,
    created_by
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3
)
RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models
`

type CreateModelRouterInstallationParams struct {
	ExternalID string
	Name       string
	CreatedBy  *string
}

// CreateModelRouterInstallation
//
//	INSERT INTO router.model_router_installations (
//	    external_id,
//	    name,
//	    created_by
//	)
//	VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3
//	)
//	RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models
func (q *Queries) CreateModelRouterInstallation(ctx context.Context, arg CreateModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, createModelRouterInstallation, arg.ExternalID, arg.Name, arg.CreatedBy)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.ExcludedModels,
	)
	return i, err
}

const getModelRouterInstallation = `-- name: GetModelRouterInstallation :one
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models
FROM router.model_router_installations
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type GetModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Gets an installation by id, scoped to an external_id to prevent cross-tenant access.
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models
//	FROM router.model_router_installations
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) GetModelRouterInstallation(ctx context.Context, arg GetModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, getModelRouterInstallation, arg.ID, arg.ExternalID)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.ExcludedModels,
	)
	return i, err
}

const listModelRouterInstallationsForExternalID = `-- name: ListModelRouterInstallationsForExternalID :many
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models
FROM router.model_router_installations
WHERE external_id = $1::varchar
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// ListModelRouterInstallationsForExternalID
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models
//	FROM router.model_router_installations
//	WHERE external_id = $1::varchar
//	  AND deleted_at IS NULL
//	ORDER BY created_at DESC
func (q *Queries) ListModelRouterInstallationsForExternalID(ctx context.Context, externalID string) ([]RouterModelRouterInstallation, error) {
	rows, err := q.db.Query(ctx, listModelRouterInstallationsForExternalID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterInstallation
	for rows.Next() {
		var i RouterModelRouterInstallation
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.ExcludedModels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteModelRouterInstallation = `-- name: SoftDeleteModelRouterInstallation :exec
UPDATE router.model_router_installations
SET deleted_at = NOW()
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type SoftDeleteModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Soft-deletes an installation, scoped to an external_id to prevent cross-tenant deletes.
//
//	UPDATE router.model_router_installations
//	SET deleted_at = NOW()
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteModelRouterInstallation(ctx context.Context, arg SoftDeleteModelRouterInstallationParams) error {
	_, err := q.db.Exec(ctx, softDeleteModelRouterInstallation, arg.ID, arg.ExternalID)
	return err
}

const updateModelRouterInstallationExcludedModels = `-- name: UpdateModelRouterInstallationExcludedModels :exec
UPDATE router.model_router_installations
SET excluded_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationExcludedModelsParams struct {
	ExcludedModels []string
	ID             uuid.UUID
}

// Replaces the per-installation model exclusion list. Empty array means
// "no exclusion". Bumps updated_at so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET excluded_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationExcludedModels(ctx context.Context, arg UpdateModelRouterInstallationExcludedModelsParams) error {
	_, err := q.db.Exec(ctx, updateModelRouterInstallationExcludedModels, arg.ExcludedModels, arg.ID)
	return err
}
