// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getModelRouterUser = `-- name: GetModelRouterUser :one
SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at
FROM router.model_router_users
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Single-row read by id; returns sql.ErrNoRows when missing or soft-deleted.
//
//	SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at
//	FROM router.model_router_users
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) GetModelRouterUser(ctx context.Context, id uuid.UUID) (RouterModelRouterUser, error) {
	row := q.db.QueryRow(ctx, getModelRouterUser, id)
	var i RouterModelRouterUser
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Email,
		&i.ClaudeAccountUUID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const listModelRouterUsersForInstallation = `-- name: ListModelRouterUsersForInstallation :many
SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at
FROM router.model_router_users
WHERE installation_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY last_seen_at DESC
`

// Lists active users for an installation (admin / dashboard; not on the request path).
//
//	SELECT id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at
//	FROM router.model_router_users
//	WHERE installation_id = $1::uuid
//	  AND deleted_at IS NULL
//	ORDER BY last_seen_at DESC
func (q *Queries) ListModelRouterUsersForInstallation(ctx context.Context, installationID uuid.UUID) ([]RouterModelRouterUser, error) {
	rows, err := q.db.Query(ctx, listModelRouterUsersForInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterUser
	for rows.Next() {
		var i RouterModelRouterUser
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Email,
			&i.ClaudeAccountUUID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelRouterUser = `-- name: UpsertModelRouterUser :one
INSERT INTO router.model_router_users (
    installation_id,
    email,
    claude_account_uuid
)
VALUES (
    $1::uuid,
    $2::text,
    $3::uuid
)
ON CONFLICT (installation_id, email) WHERE deleted_at IS NULL DO UPDATE SET
    last_seen_at        = CURRENT_TIMESTAMP,
    claude_account_uuid = COALESCE(EXCLUDED.claude_account_uuid, router.model_router_users.claude_account_uuid)
RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at
`

type UpsertModelRouterUserParams struct {
	InstallationID    uuid.UUID
	Email             string
	ClaudeAccountUUID pgtype.UUID
}

// Upserts an end-user identity for an installation, refreshing last_seen_at on every
// hit. claude_account_uuid is overwritten only when the new value is non-NULL so a
// request from a non-Claude-Code client can't blank out the field. Returns the row
// so the caller can stash user_id on the request context.
//
//	INSERT INTO router.model_router_users (
//	    installation_id,
//	    email,
//	    claude_account_uuid
//	)
//	VALUES (
//	    $1::uuid,
//	    $2::text,
//	    $3::uuid
//	)
//	ON CONFLICT (installation_id, email) WHERE deleted_at IS NULL DO UPDATE SET
//	    last_seen_at        = CURRENT_TIMESTAMP,
//	    claude_account_uuid = COALESCE(EXCLUDED.claude_account_uuid, router.model_router_users.claude_account_uuid)
//	RETURNING id, installation_id, email, claude_account_uuid, first_seen_at, last_seen_at, deleted_at
func (q *Queries) UpsertModelRouterUser(ctx context.Context, arg UpsertModelRouterUserParams) (RouterModelRouterUser, error) {
	row := q.db.QueryRow(ctx, upsertModelRouterUser, arg.InstallationID, arg.Email, arg.ClaudeAccountUUID)
	var i RouterModelRouterUser
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Email,
		&i.ClaudeAccountUUID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}
