// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_request_telemetry.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestForFeedback = `-- name: GetRequestForFeedback :one
SELECT
    t.decision_model,
    t.decision_provider,
    t.client_app,
    t.timestamp,
    t.router_user_id
FROM router.model_router_request_telemetry t
WHERE t.installation_id = $1::uuid
  AND t.request_id = $2::varchar
  AND t.span_type = 'router.upstream'
ORDER BY t.timestamp DESC
LIMIT 1
`

type GetRequestForFeedbackParams struct {
	InstallationID uuid.UUID
	RequestID      string
}

type GetRequestForFeedbackRow struct {
	DecisionModel    *string
	DecisionProvider *string
	ClientApp        *string
	Timestamp        pgtype.Timestamptz
	RouterUserID     pgtype.UUID
}

// Returns the routing context for a single request, used to render the
// no-login feedback page (`/f/<token>`): which model/provider served the turn,
// the client app, when it was routed, and the router user. Only router.upstream
// rows are persisted, so the filter pins to that span type. Returns
// sql.ErrNoRows when the request id is unknown for the installation.
//
//	SELECT
//	    t.decision_model,
//	    t.decision_provider,
//	    t.client_app,
//	    t.timestamp,
//	    t.router_user_id
//	FROM router.model_router_request_telemetry t
//	WHERE t.installation_id = $1::uuid
//	  AND t.request_id = $2::varchar
//	  AND t.span_type = 'router.upstream'
//	ORDER BY t.timestamp DESC
//	LIMIT 1
func (q *Queries) GetRequestForFeedback(ctx context.Context, arg GetRequestForFeedbackParams) (GetRequestForFeedbackRow, error) {
	row := q.db.QueryRow(ctx, getRequestForFeedback, arg.InstallationID, arg.RequestID)
	var i GetRequestForFeedbackRow
	err := row.Scan(
		&i.DecisionModel,
		&i.DecisionProvider,
		&i.ClientApp,
		&i.Timestamp,
		&i.RouterUserID,
	)
	return i, err
}

const getTelemetryModelBreakdownDaily = `-- name: GetTelemetryModelBreakdownDaily :many
SELECT
    date_trunc('day', timestamp)::timestamptz                                AS bucket,
    COALESCE(decision_model, '')::varchar                                    AS decision_model,
    COUNT(*)::bigint                                                          AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('day', timestamp), COALESCE(decision_model, '')
ORDER BY bucket ASC, decision_model ASC
`

type GetTelemetryModelBreakdownDailyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryModelBreakdownDailyRow struct {
	Bucket        pgtype.Timestamptz
	DecisionModel string
	RequestCount  int64
	TotalTokens   int64
	ActualCostUsd int64
}

// Per-day request/token/cost buckets grouped by decision model for one
// installation.
//
//	SELECT
//	    date_trunc('day', timestamp)::timestamptz                                AS bucket,
//	    COALESCE(decision_model, '')::varchar                                    AS decision_model,
//	    COUNT(*)::bigint                                                          AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('day', timestamp), COALESCE(decision_model, '')
//	ORDER BY bucket ASC, decision_model ASC
func (q *Queries) GetTelemetryModelBreakdownDaily(ctx context.Context, arg GetTelemetryModelBreakdownDailyParams) ([]GetTelemetryModelBreakdownDailyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryModelBreakdownDaily, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryModelBreakdownDailyRow
	for rows.Next() {
		var i GetTelemetryModelBreakdownDailyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.DecisionModel,
			&i.RequestCount,
			&i.TotalTokens,
			&i.ActualCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryModelBreakdownDailyAll = `-- name: GetTelemetryModelBreakdownDailyAll :many
SELECT
    date_trunc('day', timestamp)::timestamptz                                AS bucket,
    COALESCE(decision_model, '')::varchar                                    AS decision_model,
    COUNT(*)::bigint                                                          AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('day', timestamp), COALESCE(decision_model, '')
ORDER BY bucket ASC, decision_model ASC
`

type GetTelemetryModelBreakdownDailyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryModelBreakdownDailyAllRow struct {
	Bucket        pgtype.Timestamptz
	DecisionModel string
	RequestCount  int64
	TotalTokens   int64
	ActualCostUsd int64
}

// Per-day request/token/cost buckets grouped by decision model, across
// every installation. Admin-only.
//
//	SELECT
//	    date_trunc('day', timestamp)::timestamptz                                AS bucket,
//	    COALESCE(decision_model, '')::varchar                                    AS decision_model,
//	    COUNT(*)::bigint                                                          AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('day', timestamp), COALESCE(decision_model, '')
//	ORDER BY bucket ASC, decision_model ASC
func (q *Queries) GetTelemetryModelBreakdownDailyAll(ctx context.Context, arg GetTelemetryModelBreakdownDailyAllParams) ([]GetTelemetryModelBreakdownDailyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryModelBreakdownDailyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryModelBreakdownDailyAllRow
	for rows.Next() {
		var i GetTelemetryModelBreakdownDailyAllRow
		if err := rows.Scan(
			&i.Bucket,
			&i.DecisionModel,
			&i.RequestCount,
			&i.TotalTokens,
			&i.ActualCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryModelBreakdownHourly = `-- name: GetTelemetryModelBreakdownHourly :many
SELECT
    date_trunc('hour', timestamp)::timestamptz                               AS bucket,
    COALESCE(decision_model, '')::varchar                                    AS decision_model,
    COUNT(*)::bigint                                                          AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('hour', timestamp), COALESCE(decision_model, '')
ORDER BY bucket ASC, decision_model ASC
`

type GetTelemetryModelBreakdownHourlyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryModelBreakdownHourlyRow struct {
	Bucket        pgtype.Timestamptz
	DecisionModel string
	RequestCount  int64
	TotalTokens   int64
	ActualCostUsd int64
}

// Per-hour request/token/cost buckets grouped by decision model for one
// installation. Powers the dashboard's per-model usage and spend charts.
//
//	SELECT
//	    date_trunc('hour', timestamp)::timestamptz                               AS bucket,
//	    COALESCE(decision_model, '')::varchar                                    AS decision_model,
//	    COUNT(*)::bigint                                                          AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('hour', timestamp), COALESCE(decision_model, '')
//	ORDER BY bucket ASC, decision_model ASC
func (q *Queries) GetTelemetryModelBreakdownHourly(ctx context.Context, arg GetTelemetryModelBreakdownHourlyParams) ([]GetTelemetryModelBreakdownHourlyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryModelBreakdownHourly, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryModelBreakdownHourlyRow
	for rows.Next() {
		var i GetTelemetryModelBreakdownHourlyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.DecisionModel,
			&i.RequestCount,
			&i.TotalTokens,
			&i.ActualCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryModelBreakdownHourlyAll = `-- name: GetTelemetryModelBreakdownHourlyAll :many
SELECT
    date_trunc('hour', timestamp)::timestamptz                               AS bucket,
    COALESCE(decision_model, '')::varchar                                    AS decision_model,
    COUNT(*)::bigint                                                          AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('hour', timestamp), COALESCE(decision_model, '')
ORDER BY bucket ASC, decision_model ASC
`

type GetTelemetryModelBreakdownHourlyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryModelBreakdownHourlyAllRow struct {
	Bucket        pgtype.Timestamptz
	DecisionModel string
	RequestCount  int64
	TotalTokens   int64
	ActualCostUsd int64
}

// Per-hour request/token/cost buckets grouped by the model the router
// selected, across every installation. Powers the dashboard's per-model
// usage and spend charts. Admin-only.
//
//	SELECT
//	    date_trunc('hour', timestamp)::timestamptz                               AS bucket,
//	    COALESCE(decision_model, '')::varchar                                    AS decision_model,
//	    COUNT(*)::bigint                                                          AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('hour', timestamp), COALESCE(decision_model, '')
//	ORDER BY bucket ASC, decision_model ASC
func (q *Queries) GetTelemetryModelBreakdownHourlyAll(ctx context.Context, arg GetTelemetryModelBreakdownHourlyAllParams) ([]GetTelemetryModelBreakdownHourlyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryModelBreakdownHourlyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryModelBreakdownHourlyAllRow
	for rows.Next() {
		var i GetTelemetryModelBreakdownHourlyAllRow
		if err := rows.Scan(
			&i.Bucket,
			&i.DecisionModel,
			&i.RequestCount,
			&i.TotalTokens,
			&i.ActualCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryModelBreakdownWeekly = `-- name: GetTelemetryModelBreakdownWeekly :many
SELECT
    date_trunc('week', timestamp)::timestamptz                               AS bucket,
    COALESCE(decision_model, '')::varchar                                    AS decision_model,
    COUNT(*)::bigint                                                          AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('week', timestamp), COALESCE(decision_model, '')
ORDER BY bucket ASC, decision_model ASC
`

type GetTelemetryModelBreakdownWeeklyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryModelBreakdownWeeklyRow struct {
	Bucket        pgtype.Timestamptz
	DecisionModel string
	RequestCount  int64
	TotalTokens   int64
	ActualCostUsd int64
}

// Per-ISO-week request/token/cost buckets grouped by decision model for
// one installation.
//
//	SELECT
//	    date_trunc('week', timestamp)::timestamptz                               AS bucket,
//	    COALESCE(decision_model, '')::varchar                                    AS decision_model,
//	    COUNT(*)::bigint                                                          AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('week', timestamp), COALESCE(decision_model, '')
//	ORDER BY bucket ASC, decision_model ASC
func (q *Queries) GetTelemetryModelBreakdownWeekly(ctx context.Context, arg GetTelemetryModelBreakdownWeeklyParams) ([]GetTelemetryModelBreakdownWeeklyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryModelBreakdownWeekly, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryModelBreakdownWeeklyRow
	for rows.Next() {
		var i GetTelemetryModelBreakdownWeeklyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.DecisionModel,
			&i.RequestCount,
			&i.TotalTokens,
			&i.ActualCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryModelBreakdownWeeklyAll = `-- name: GetTelemetryModelBreakdownWeeklyAll :many
SELECT
    date_trunc('week', timestamp)::timestamptz                               AS bucket,
    COALESCE(decision_model, '')::varchar                                    AS decision_model,
    COUNT(*)::bigint                                                          AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('week', timestamp), COALESCE(decision_model, '')
ORDER BY bucket ASC, decision_model ASC
`

type GetTelemetryModelBreakdownWeeklyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryModelBreakdownWeeklyAllRow struct {
	Bucket        pgtype.Timestamptz
	DecisionModel string
	RequestCount  int64
	TotalTokens   int64
	ActualCostUsd int64
}

// Per-ISO-week request/token/cost buckets grouped by decision model,
// across every installation. Admin-only.
//
//	SELECT
//	    date_trunc('week', timestamp)::timestamptz                               AS bucket,
//	    COALESCE(decision_model, '')::varchar                                    AS decision_model,
//	    COUNT(*)::bigint                                                          AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint                   AS total_tokens,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('week', timestamp), COALESCE(decision_model, '')
//	ORDER BY bucket ASC, decision_model ASC
func (q *Queries) GetTelemetryModelBreakdownWeeklyAll(ctx context.Context, arg GetTelemetryModelBreakdownWeeklyAllParams) ([]GetTelemetryModelBreakdownWeeklyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryModelBreakdownWeeklyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryModelBreakdownWeeklyAllRow
	for rows.Next() {
		var i GetTelemetryModelBreakdownWeeklyAllRow
		if err := rows.Scan(
			&i.Bucket,
			&i.DecisionModel,
			&i.RequestCount,
			&i.TotalTokens,
			&i.ActualCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryRows = `-- name: GetTelemetryRows :many
SELECT
    t.timestamp,
    t.request_id,
    t.requested_model,
    t.decision_model,
    t.decision_provider,
    t.decision_reason,
    t.sticky_hit,
    t.input_tokens,
    t.output_tokens,
    t.cache_creation_tokens,
    t.cache_read_tokens,
    COALESCE(t.requested_input_cost_usd + t.requested_output_cost_usd, 0)::bigint AS requested_cost_usd,
    COALESCE(t.actual_input_cost_usd + t.actual_output_cost_usd, 0)::bigint       AS actual_cost_usd,
    t.total_latency_ms,
    t.upstream_status_code,
    t.router_user_id,
    t.client_app,
    COALESCE(t.turn_type, '')::varchar AS turn_type,
    u.email AS user_email
FROM router.model_router_request_telemetry t
LEFT JOIN router.model_router_users u
    ON u.id = t.router_user_id
    AND u.deleted_at IS NULL
WHERE t.installation_id = $1::uuid
  AND t.span_type = 'router.upstream'
  AND t.timestamp >= $2::timestamptz
  AND t.timestamp < $3::timestamptz
ORDER BY t.timestamp DESC
LIMIT $4::int
`

type GetTelemetryRowsParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
	RowLimit       int32
}

type GetTelemetryRowsRow struct {
	Timestamp           pgtype.Timestamptz
	RequestID           string
	RequestedModel      *string
	DecisionModel       *string
	DecisionProvider    *string
	DecisionReason      *string
	StickyHit           *bool
	InputTokens         *int32
	OutputTokens        *int32
	CacheCreationTokens *int32
	CacheReadTokens     *int32
	RequestedCostUsd    int64
	ActualCostUsd       int64
	TotalLatencyMs      *int64
	UpstreamStatusCode  *int32
	RouterUserID        pgtype.UUID
	ClientApp           *string
	TurnType            string
	UserEmail           *string
}

// Returns individual telemetry rows scoped to a single installation.
//
//	SELECT
//	    t.timestamp,
//	    t.request_id,
//	    t.requested_model,
//	    t.decision_model,
//	    t.decision_provider,
//	    t.decision_reason,
//	    t.sticky_hit,
//	    t.input_tokens,
//	    t.output_tokens,
//	    t.cache_creation_tokens,
//	    t.cache_read_tokens,
//	    COALESCE(t.requested_input_cost_usd + t.requested_output_cost_usd, 0)::bigint AS requested_cost_usd,
//	    COALESCE(t.actual_input_cost_usd + t.actual_output_cost_usd, 0)::bigint       AS actual_cost_usd,
//	    t.total_latency_ms,
//	    t.upstream_status_code,
//	    t.router_user_id,
//	    t.client_app,
//	    COALESCE(t.turn_type, '')::varchar AS turn_type,
//	    u.email AS user_email
//	FROM router.model_router_request_telemetry t
//	LEFT JOIN router.model_router_users u
//	    ON u.id = t.router_user_id
//	    AND u.deleted_at IS NULL
//	WHERE t.installation_id = $1::uuid
//	  AND t.span_type = 'router.upstream'
//	  AND t.timestamp >= $2::timestamptz
//	  AND t.timestamp < $3::timestamptz
//	ORDER BY t.timestamp DESC
//	LIMIT $4::int
func (q *Queries) GetTelemetryRows(ctx context.Context, arg GetTelemetryRowsParams) ([]GetTelemetryRowsRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryRows,
		arg.InstallationID,
		arg.FromTime,
		arg.ToTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryRowsRow
	for rows.Next() {
		var i GetTelemetryRowsRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.RequestID,
			&i.RequestedModel,
			&i.DecisionModel,
			&i.DecisionProvider,
			&i.DecisionReason,
			&i.StickyHit,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.RequestedCostUsd,
			&i.ActualCostUsd,
			&i.TotalLatencyMs,
			&i.UpstreamStatusCode,
			&i.RouterUserID,
			&i.ClientApp,
			&i.TurnType,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryRowsAll = `-- name: GetTelemetryRowsAll :many
SELECT
    t.timestamp,
    t.request_id,
    t.requested_model,
    t.decision_model,
    t.decision_provider,
    t.decision_reason,
    t.sticky_hit,
    t.input_tokens,
    t.output_tokens,
    t.cache_creation_tokens,
    t.cache_read_tokens,
    COALESCE(t.requested_input_cost_usd + t.requested_output_cost_usd, 0)::bigint AS requested_cost_usd,
    COALESCE(t.actual_input_cost_usd + t.actual_output_cost_usd, 0)::bigint       AS actual_cost_usd,
    t.total_latency_ms,
    t.upstream_status_code,
    t.router_user_id,
    t.client_app,
    COALESCE(t.turn_type, '')::varchar AS turn_type,
    u.email AS user_email
FROM router.model_router_request_telemetry t
LEFT JOIN router.model_router_users u
    ON u.id = t.router_user_id
    AND u.deleted_at IS NULL
WHERE t.span_type = 'router.upstream'
  AND t.timestamp >= $1::timestamptz
  AND t.timestamp < $2::timestamptz
ORDER BY t.timestamp DESC
LIMIT $3::int
`

type GetTelemetryRowsAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
	RowLimit int32
}

type GetTelemetryRowsAllRow struct {
	Timestamp           pgtype.Timestamptz
	RequestID           string
	RequestedModel      *string
	DecisionModel       *string
	DecisionProvider    *string
	DecisionReason      *string
	StickyHit           *bool
	InputTokens         *int32
	OutputTokens        *int32
	CacheCreationTokens *int32
	CacheReadTokens     *int32
	RequestedCostUsd    int64
	ActualCostUsd       int64
	TotalLatencyMs      *int64
	UpstreamStatusCode  *int32
	RouterUserID        pgtype.UUID
	ClientApp           *string
	TurnType            string
	UserEmail           *string
}

// Returns individual telemetry rows for a time window. Used by the
// dashboard drill-down modal to show the underlying requests behind a
// chart bucket. Admin scope: spans every installation.
//
//	SELECT
//	    t.timestamp,
//	    t.request_id,
//	    t.requested_model,
//	    t.decision_model,
//	    t.decision_provider,
//	    t.decision_reason,
//	    t.sticky_hit,
//	    t.input_tokens,
//	    t.output_tokens,
//	    t.cache_creation_tokens,
//	    t.cache_read_tokens,
//	    COALESCE(t.requested_input_cost_usd + t.requested_output_cost_usd, 0)::bigint AS requested_cost_usd,
//	    COALESCE(t.actual_input_cost_usd + t.actual_output_cost_usd, 0)::bigint       AS actual_cost_usd,
//	    t.total_latency_ms,
//	    t.upstream_status_code,
//	    t.router_user_id,
//	    t.client_app,
//	    COALESCE(t.turn_type, '')::varchar AS turn_type,
//	    u.email AS user_email
//	FROM router.model_router_request_telemetry t
//	LEFT JOIN router.model_router_users u
//	    ON u.id = t.router_user_id
//	    AND u.deleted_at IS NULL
//	WHERE t.span_type = 'router.upstream'
//	  AND t.timestamp >= $1::timestamptz
//	  AND t.timestamp < $2::timestamptz
//	ORDER BY t.timestamp DESC
//	LIMIT $3::int
func (q *Queries) GetTelemetryRowsAll(ctx context.Context, arg GetTelemetryRowsAllParams) ([]GetTelemetryRowsAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryRowsAll, arg.FromTime, arg.ToTime, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryRowsAllRow
	for rows.Next() {
		var i GetTelemetryRowsAllRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.RequestID,
			&i.RequestedModel,
			&i.DecisionModel,
			&i.DecisionProvider,
			&i.DecisionReason,
			&i.StickyHit,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.RequestedCostUsd,
			&i.ActualCostUsd,
			&i.TotalLatencyMs,
			&i.UpstreamStatusCode,
			&i.RouterUserID,
			&i.ClientApp,
			&i.TurnType,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetrySummary = `-- name: GetTelemetrySummary :one
SELECT
    COUNT(*)::bigint                                            AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS total_requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS total_actual_cost_usd,
    COALESCE(SUM(
        (requested_input_cost_usd + requested_output_cost_usd) -
        (actual_input_cost_usd + actual_output_cost_usd)
    ), 0)::bigint                                             AS total_savings_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
`

type GetTelemetrySummaryParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetrySummaryRow struct {
	RequestCount          int64
	TotalTokens           int64
	TotalRequestedCostUsd int64
	TotalActualCostUsd    int64
	TotalSavingsUsd       int64
}

// Returns aggregated cost and token totals for the dashboard cards.
//
//	SELECT
//	    COUNT(*)::bigint                                            AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS total_requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS total_actual_cost_usd,
//	    COALESCE(SUM(
//	        (requested_input_cost_usd + requested_output_cost_usd) -
//	        (actual_input_cost_usd + actual_output_cost_usd)
//	    ), 0)::bigint                                             AS total_savings_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
func (q *Queries) GetTelemetrySummary(ctx context.Context, arg GetTelemetrySummaryParams) (GetTelemetrySummaryRow, error) {
	row := q.db.QueryRow(ctx, getTelemetrySummary, arg.InstallationID, arg.FromTime, arg.ToTime)
	var i GetTelemetrySummaryRow
	err := row.Scan(
		&i.RequestCount,
		&i.TotalTokens,
		&i.TotalRequestedCostUsd,
		&i.TotalActualCostUsd,
		&i.TotalSavingsUsd,
	)
	return i, err
}

const getTelemetrySummaryAll = `-- name: GetTelemetrySummaryAll :one
SELECT
    COUNT(*)::bigint                                            AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS total_requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS total_actual_cost_usd,
    COALESCE(SUM(
        (requested_input_cost_usd + requested_output_cost_usd) -
        (actual_input_cost_usd + actual_output_cost_usd)
    ), 0)::bigint                                             AS total_savings_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
`

type GetTelemetrySummaryAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetrySummaryAllRow struct {
	RequestCount          int64
	TotalTokens           int64
	TotalRequestedCostUsd int64
	TotalActualCostUsd    int64
	TotalSavingsUsd       int64
}

// Returns aggregated cost and token totals across every installation.
// Used by admin-cookie sessions on the dashboard, which are not scoped to
// a single rk_ key.
//
//	SELECT
//	    COUNT(*)::bigint                                            AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS total_requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS total_actual_cost_usd,
//	    COALESCE(SUM(
//	        (requested_input_cost_usd + requested_output_cost_usd) -
//	        (actual_input_cost_usd + actual_output_cost_usd)
//	    ), 0)::bigint                                             AS total_savings_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
func (q *Queries) GetTelemetrySummaryAll(ctx context.Context, arg GetTelemetrySummaryAllParams) (GetTelemetrySummaryAllRow, error) {
	row := q.db.QueryRow(ctx, getTelemetrySummaryAll, arg.FromTime, arg.ToTime)
	var i GetTelemetrySummaryAllRow
	err := row.Scan(
		&i.RequestCount,
		&i.TotalTokens,
		&i.TotalRequestedCostUsd,
		&i.TotalActualCostUsd,
		&i.TotalSavingsUsd,
	)
	return i, err
}

const getTelemetryTimeseriesDaily = `-- name: GetTelemetryTimeseriesDaily :many
SELECT
    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('day', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesDailyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryTimeseriesDailyRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd int64
	ActualCostUsd    int64
}

// Returns per-day cost buckets for the cost savings chart.
//
//	SELECT
//	    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('day', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesDaily(ctx context.Context, arg GetTelemetryTimeseriesDailyParams) ([]GetTelemetryTimeseriesDailyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesDaily, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesDailyRow
	for rows.Next() {
		var i GetTelemetryTimeseriesDailyRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesDailyAll = `-- name: GetTelemetryTimeseriesDailyAll :many
SELECT
    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('day', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesDailyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryTimeseriesDailyAllRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd int64
	ActualCostUsd    int64
}

// Per-day cost buckets across every installation. Admin-only.
//
//	SELECT
//	    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('day', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesDailyAll(ctx context.Context, arg GetTelemetryTimeseriesDailyAllParams) ([]GetTelemetryTimeseriesDailyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesDailyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesDailyAllRow
	for rows.Next() {
		var i GetTelemetryTimeseriesDailyAllRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesHourly = `-- name: GetTelemetryTimeseriesHourly :many
SELECT
    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('hour', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesHourlyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryTimeseriesHourlyRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd int64
	ActualCostUsd    int64
}

// Returns per-hour cost buckets for the cost savings chart.
//
//	SELECT
//	    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('hour', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesHourly(ctx context.Context, arg GetTelemetryTimeseriesHourlyParams) ([]GetTelemetryTimeseriesHourlyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesHourly, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesHourlyRow
	for rows.Next() {
		var i GetTelemetryTimeseriesHourlyRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesHourlyAll = `-- name: GetTelemetryTimeseriesHourlyAll :many
SELECT
    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('hour', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesHourlyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryTimeseriesHourlyAllRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd int64
	ActualCostUsd    int64
}

// Per-hour cost buckets across every installation. Admin-only.
//
//	SELECT
//	    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('hour', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesHourlyAll(ctx context.Context, arg GetTelemetryTimeseriesHourlyAllParams) ([]GetTelemetryTimeseriesHourlyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesHourlyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesHourlyAllRow
	for rows.Next() {
		var i GetTelemetryTimeseriesHourlyAllRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesWeekly = `-- name: GetTelemetryTimeseriesWeekly :many
SELECT
    date_trunc('week', timestamp)::timestamptz                                       AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('week', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesWeeklyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryTimeseriesWeeklyRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd int64
	ActualCostUsd    int64
}

// Returns per-ISO-week cost buckets for the cost savings chart.
//
//	SELECT
//	    date_trunc('week', timestamp)::timestamptz                                       AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('week', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesWeekly(ctx context.Context, arg GetTelemetryTimeseriesWeeklyParams) ([]GetTelemetryTimeseriesWeeklyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesWeekly, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesWeeklyRow
	for rows.Next() {
		var i GetTelemetryTimeseriesWeeklyRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesWeeklyAll = `-- name: GetTelemetryTimeseriesWeeklyAll :many
SELECT
    date_trunc('week', timestamp)::timestamptz                                       AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('week', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesWeeklyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryTimeseriesWeeklyAllRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd int64
	ActualCostUsd    int64
}

// Per-ISO-week cost buckets across every installation. Admin-only.
//
//	SELECT
//	    date_trunc('week', timestamp)::timestamptz                                       AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::bigint AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::bigint       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('week', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesWeeklyAll(ctx context.Context, arg GetTelemetryTimeseriesWeeklyAllParams) ([]GetTelemetryTimeseriesWeeklyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesWeeklyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesWeeklyAllRow
	for rows.Next() {
		var i GetTelemetryTimeseriesWeeklyAllRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRequestTelemetry = `-- name: InsertRequestTelemetry :exec
INSERT INTO router.model_router_request_telemetry (
    installation_id,
    api_key_id,
    request_id,
    span_type,
    trace_id,
    timestamp,
    requested_model,
    decision_model,
    decision_provider,
    decision_reason,
    estimated_input_tokens,
    sticky_hit,
    embed_input,
    input_tokens,
    output_tokens,
    requested_input_cost_usd,
    requested_output_cost_usd,
    actual_input_cost_usd,
    actual_output_cost_usd,
    route_latency_ms,
    upstream_latency_ms,
    total_latency_ms,
    cross_format,
    upstream_status_code,
    cluster_ids,
    candidate_models,
    chosen_score,
    candidate_scores,
    propensity,
    alpha_breakdown,
    cluster_router_version,
    strategy,
    route_id,
    policy_route_key,
    policy_artifact_id,
    policy_artifact_sha256,
    roster_version,
    sidecar_schema_version,
    training_allowed,
    capture_mode,
    debug_ref,
    ttft_ms,
    cache_creation_tokens,
    cache_read_tokens,
    device_id,
    session_id,
    router_user_id,
    client_app,
    turn_type,
    rollout_id,
    upstream_finish_reason,
    stop_reason,
    tool_use_blocks,
    invalid_tool_args_blocks,
    failover_used,
    degenerate_shadow,
    session_key,
    role,
    fresh_decision_model,
    fresh_candidate_scores,
    pin_age_sec,
    tool_result_bytes,
    credential_key_prefix,
    credential_key_suffix,
    credential_source
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::timestamptz,
    $7::varchar,
    $8::varchar,
    $9::varchar,
    $10::varchar,
    $11::int,
    $12::boolean,
    $13::varchar,
    $14::int,
    $15::int,
    $16::bigint,
    $17::bigint,
    $18::bigint,
    $19::bigint,
    $20::bigint,
    $21::bigint,
    $22::bigint,
    $23::boolean,
    $24::int,
    $25::int[],
    $26::text[],
    $27::double precision,
    $28::jsonb,
    $29::double precision,
    $30::jsonb,
    $31::varchar,
    $32::varchar,
    $33::varchar,
    $34::varchar,
    $35::varchar,
    $36::varchar,
    $37::varchar,
    $38::varchar,
    $39::boolean,
    $40::varchar,
    $41::varchar,
    $42::bigint,
    $43::int,
    $44::int,
    $45::varchar,
    $46::varchar,
    $47::uuid,
    $48::text,
    $49::varchar,
    $50::varchar,
    $51::text,
    $52::text,
    $53::int,
    $54::int,
    $55::boolean,
    $56::boolean,
    $57::bytea,
    $58::varchar,
    $59::varchar,
    $60::jsonb,
    $61::bigint,
    $62::int,
    $63::varchar,
    $64::varchar,
    $65::varchar
)
ON CONFLICT (installation_id, request_id, span_type) DO NOTHING
`

type InsertRequestTelemetryParams struct {
	InstallationID         uuid.UUID
	APIKeyID               pgtype.UUID
	RequestID              string
	SpanType               string
	TraceID                string
	Timestamp              pgtype.Timestamptz
	RequestedModel         string
	DecisionModel          string
	DecisionProvider       string
	DecisionReason         string
	EstimatedInputTokens   int32
	StickyHit              bool
	EmbedInput             string
	InputTokens            int32
	OutputTokens           int32
	RequestedInputCostUsd  int64
	RequestedOutputCostUsd int64
	ActualInputCostUsd     int64
	ActualOutputCostUsd    int64
	RouteLatencyMs         int64
	UpstreamLatencyMs      int64
	TotalLatencyMs         int64
	CrossFormat            bool
	UpstreamStatusCode     int32
	ClusterIds             []int32
	CandidateModels        []string
	ChosenScore            *float64
	CandidateScores        []byte
	Propensity             *float64
	AlphaBreakdown         []byte
	ClusterRouterVersion   *string
	Strategy               *string
	RouteID                *string
	PolicyRouteKey         *string
	PolicyArtifactID       *string
	PolicyArtifactSha256   *string
	RosterVersion          *string
	SidecarSchemaVersion   *string
	TrainingAllowed        bool
	CaptureMode            string
	DebugRef               *string
	TtftMs                 *int64
	CacheCreationTokens    *int32
	CacheReadTokens        *int32
	DeviceID               *string
	SessionID              *string
	RouterUserID           pgtype.UUID
	ClientApp              *string
	TurnType               string
	RolloutID              *string
	UpstreamFinishReason   *string
	StopReason             *string
	ToolUseBlocks          *int32
	InvalidToolArgsBlocks  *int32
	FailoverUsed           *bool
	DegenerateShadow       *bool
	SessionKey             []byte
	Role                   *string
	FreshDecisionModel     *string
	FreshCandidateScores   []byte
	PinAgeSec              *int64
	ToolResultBytes        *int32
	CredentialKeyPrefix    *string
	CredentialKeySuffix    *string
	CredentialSource       *string
}

// Records a completed proxied request for the dashboard UI and routing
// observability. Routing-brain fields (cluster_ids, candidate_models,
// chosen_score, candidate_scores, propensity, alpha_breakdown,
// cluster_router_version, ttft_ms, cache_*_tokens, device_id, session_id) are
// nullable; non-cluster decisions and pinned-route turns leave them NULL.
// turn_type is the turntype classification (main_loop, tool_result, probe,
// title_gen, compaction, classifier, sub_agent_dispatch); NULL only on rows
// written before the column existed.
// rollout_id is the client-supplied x-weave-rollout-id correlation id used by
// eval/training harnesses to join graded rollout rewards onto decisions; NULL
// for all non-harness traffic.
// session_key + role are the offline join key to router.spiral_shadow_events
// and session_pins; NULL on rows written before the columns existed.
// fresh_decision_model + fresh_candidate_scores capture the scorer's fresh
// recommendation even on STAY turns (where decision_model names the pinned
// model served); pin_age_sec supports min-dwell analysis. Shadow-mode
// instrumentation for the hysteresis downgrade lever; NULL when the scorer did
// not run / no pin was loaded.
// credential_key_prefix + credential_key_suffix are the safe display parts of
// the upstream credential; credential_source names the precedence branch it came
// from. All NULL on deployment-key turns. Matching prefix/suffix values across
// distinct router_user_ids reveal one subscription paying for many seats.
//
//	INSERT INTO router.model_router_request_telemetry (
//	    installation_id,
//	    api_key_id,
//	    request_id,
//	    span_type,
//	    trace_id,
//	    timestamp,
//	    requested_model,
//	    decision_model,
//	    decision_provider,
//	    decision_reason,
//	    estimated_input_tokens,
//	    sticky_hit,
//	    embed_input,
//	    input_tokens,
//	    output_tokens,
//	    requested_input_cost_usd,
//	    requested_output_cost_usd,
//	    actual_input_cost_usd,
//	    actual_output_cost_usd,
//	    route_latency_ms,
//	    upstream_latency_ms,
//	    total_latency_ms,
//	    cross_format,
//	    upstream_status_code,
//	    cluster_ids,
//	    candidate_models,
//	    chosen_score,
//	    candidate_scores,
//	    propensity,
//	    alpha_breakdown,
//	    cluster_router_version,
//	    strategy,
//	    route_id,
//	    policy_route_key,
//	    policy_artifact_id,
//	    policy_artifact_sha256,
//	    roster_version,
//	    sidecar_schema_version,
//	    training_allowed,
//	    capture_mode,
//	    debug_ref,
//	    ttft_ms,
//	    cache_creation_tokens,
//	    cache_read_tokens,
//	    device_id,
//	    session_id,
//	    router_user_id,
//	    client_app,
//	    turn_type,
//	    rollout_id,
//	    upstream_finish_reason,
//	    stop_reason,
//	    tool_use_blocks,
//	    invalid_tool_args_blocks,
//	    failover_used,
//	    degenerate_shadow,
//	    session_key,
//	    role,
//	    fresh_decision_model,
//	    fresh_candidate_scores,
//	    pin_age_sec,
//	    tool_result_bytes,
//	    credential_key_prefix,
//	    credential_key_suffix,
//	    credential_source
//	) VALUES (
//	    $1::uuid,
//	    $2::uuid,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::timestamptz,
//	    $7::varchar,
//	    $8::varchar,
//	    $9::varchar,
//	    $10::varchar,
//	    $11::int,
//	    $12::boolean,
//	    $13::varchar,
//	    $14::int,
//	    $15::int,
//	    $16::bigint,
//	    $17::bigint,
//	    $18::bigint,
//	    $19::bigint,
//	    $20::bigint,
//	    $21::bigint,
//	    $22::bigint,
//	    $23::boolean,
//	    $24::int,
//	    $25::int[],
//	    $26::text[],
//	    $27::double precision,
//	    $28::jsonb,
//	    $29::double precision,
//	    $30::jsonb,
//	    $31::varchar,
//	    $32::varchar,
//	    $33::varchar,
//	    $34::varchar,
//	    $35::varchar,
//	    $36::varchar,
//	    $37::varchar,
//	    $38::varchar,
//	    $39::boolean,
//	    $40::varchar,
//	    $41::varchar,
//	    $42::bigint,
//	    $43::int,
//	    $44::int,
//	    $45::varchar,
//	    $46::varchar,
//	    $47::uuid,
//	    $48::text,
//	    $49::varchar,
//	    $50::varchar,
//	    $51::text,
//	    $52::text,
//	    $53::int,
//	    $54::int,
//	    $55::boolean,
//	    $56::boolean,
//	    $57::bytea,
//	    $58::varchar,
//	    $59::varchar,
//	    $60::jsonb,
//	    $61::bigint,
//	    $62::int,
//	    $63::varchar,
//	    $64::varchar,
//	    $65::varchar
//	)
//	ON CONFLICT (installation_id, request_id, span_type) DO NOTHING
func (q *Queries) InsertRequestTelemetry(ctx context.Context, arg InsertRequestTelemetryParams) error {
	_, err := q.db.Exec(ctx, insertRequestTelemetry,
		arg.InstallationID,
		arg.APIKeyID,
		arg.RequestID,
		arg.SpanType,
		arg.TraceID,
		arg.Timestamp,
		arg.RequestedModel,
		arg.DecisionModel,
		arg.DecisionProvider,
		arg.DecisionReason,
		arg.EstimatedInputTokens,
		arg.StickyHit,
		arg.EmbedInput,
		arg.InputTokens,
		arg.OutputTokens,
		arg.RequestedInputCostUsd,
		arg.RequestedOutputCostUsd,
		arg.ActualInputCostUsd,
		arg.ActualOutputCostUsd,
		arg.RouteLatencyMs,
		arg.UpstreamLatencyMs,
		arg.TotalLatencyMs,
		arg.CrossFormat,
		arg.UpstreamStatusCode,
		arg.ClusterIds,
		arg.CandidateModels,
		arg.ChosenScore,
		arg.CandidateScores,
		arg.Propensity,
		arg.AlphaBreakdown,
		arg.ClusterRouterVersion,
		arg.Strategy,
		arg.RouteID,
		arg.PolicyRouteKey,
		arg.PolicyArtifactID,
		arg.PolicyArtifactSha256,
		arg.RosterVersion,
		arg.SidecarSchemaVersion,
		arg.TrainingAllowed,
		arg.CaptureMode,
		arg.DebugRef,
		arg.TtftMs,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
		arg.DeviceID,
		arg.SessionID,
		arg.RouterUserID,
		arg.ClientApp,
		arg.TurnType,
		arg.RolloutID,
		arg.UpstreamFinishReason,
		arg.StopReason,
		arg.ToolUseBlocks,
		arg.InvalidToolArgsBlocks,
		arg.FailoverUsed,
		arg.DegenerateShadow,
		arg.SessionKey,
		arg.Role,
		arg.FreshDecisionModel,
		arg.FreshCandidateScores,
		arg.PinAgeSec,
		arg.ToolResultBytes,
		arg.CredentialKeyPrefix,
		arg.CredentialKeySuffix,
		arg.CredentialSource,
	)
	return err
}
