// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Rotatable bearer keys (rk_ prefix) per installation
type RouterModelRouterAPIKey struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	ExternalID     string
	Name           *string
	KeyPrefix      string
	// SHA-256 of the full rk_ token
	KeyHash string
	// Last 4 chars for display
	KeySuffix  string
	LastUsedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
	CreatedBy  *string
}

// Customer-owned provider API keys for BYOK routing
type RouterModelRouterExternalAPIKey struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	ExternalID     string
	Provider       string
	// AES-256-GCM encrypted API key with 12-byte nonce prepended
	KeyCiphertext []byte
	KeyPrefix     string
	KeySuffix     string
	// SHA-256 of plaintext for deduplication display
	KeyFingerprint string
	Name           *string
	LastUsedAt     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	CreatedBy      *string
}

// Customer router installations; owns API keys
type RouterModelRouterInstallation struct {
	ID         uuid.UUID
	ExternalID string
	Name       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
	CreatedBy  *string
}

// End-user identities seen on inbound requests, scoped to an installation. Replaces the per-user API key pattern.
type RouterModelRouterUser struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	// Lowercased, trimmed user email (typically git user.email). Application-normalized; column is plain TEXT.
	Email string
	// Optional Claude Code account_uuid carried in metadata.user_id; informational only.
	ClaudeAccountUUID pgtype.UUID
	FirstSeenAt       pgtype.Timestamp
	LastSeenAt        pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
}

// Session-sticky routing pins; sliding 1h TTL matching Anthropic prompt cache
type RouterSessionPin struct {
	// 16-byte digest derived from api_key_id + (metadata.user_id | system+first-user hashes)
	SessionKey []byte
	// Stage 1 always emits "default"; turn-type roles land with §3.3
	Role           string
	InstallationID uuid.UUID
	PinnedProvider string
	PinnedModel    string
	DecisionReason string
	TurnCount      int32
	PinnedUntil    pgtype.Timestamp
	FirstPinnedAt  pgtype.Timestamp
	LastSeenAt     pgtype.Timestamp
}
