// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_request_telemetry.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTelemetrySummary = `-- name: GetTelemetrySummary :one
SELECT
    COUNT(*)::bigint                                            AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS total_requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS total_actual_cost_usd,
    COALESCE(SUM(
        (requested_input_cost_usd + requested_output_cost_usd) -
        (actual_input_cost_usd + actual_output_cost_usd)
    ), 0)::numeric                                             AS total_savings_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
`

type GetTelemetrySummaryParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetrySummaryRow struct {
	RequestCount          int64
	TotalTokens           int64
	TotalRequestedCostUsd pgtype.Numeric
	TotalActualCostUsd    pgtype.Numeric
	TotalSavingsUsd       pgtype.Numeric
}

// Returns aggregated cost and token totals for the dashboard cards.
//
//	SELECT
//	    COUNT(*)::bigint                                            AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS total_requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS total_actual_cost_usd,
//	    COALESCE(SUM(
//	        (requested_input_cost_usd + requested_output_cost_usd) -
//	        (actual_input_cost_usd + actual_output_cost_usd)
//	    ), 0)::numeric                                             AS total_savings_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
func (q *Queries) GetTelemetrySummary(ctx context.Context, arg GetTelemetrySummaryParams) (GetTelemetrySummaryRow, error) {
	row := q.db.QueryRow(ctx, getTelemetrySummary, arg.InstallationID, arg.FromTime, arg.ToTime)
	var i GetTelemetrySummaryRow
	err := row.Scan(
		&i.RequestCount,
		&i.TotalTokens,
		&i.TotalRequestedCostUsd,
		&i.TotalActualCostUsd,
		&i.TotalSavingsUsd,
	)
	return i, err
}

const getTelemetrySummaryAll = `-- name: GetTelemetrySummaryAll :one
SELECT
    COUNT(*)::bigint                                            AS request_count,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS total_requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS total_actual_cost_usd,
    COALESCE(SUM(
        (requested_input_cost_usd + requested_output_cost_usd) -
        (actual_input_cost_usd + actual_output_cost_usd)
    ), 0)::numeric                                             AS total_savings_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
`

type GetTelemetrySummaryAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetrySummaryAllRow struct {
	RequestCount          int64
	TotalTokens           int64
	TotalRequestedCostUsd pgtype.Numeric
	TotalActualCostUsd    pgtype.Numeric
	TotalSavingsUsd       pgtype.Numeric
}

// Returns aggregated cost and token totals across every installation.
// Used by admin-cookie sessions on the dashboard, which are not scoped to
// a single rk_ key.
//
//	SELECT
//	    COUNT(*)::bigint                                            AS request_count,
//	    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint     AS total_tokens,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS total_requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS total_actual_cost_usd,
//	    COALESCE(SUM(
//	        (requested_input_cost_usd + requested_output_cost_usd) -
//	        (actual_input_cost_usd + actual_output_cost_usd)
//	    ), 0)::numeric                                             AS total_savings_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
func (q *Queries) GetTelemetrySummaryAll(ctx context.Context, arg GetTelemetrySummaryAllParams) (GetTelemetrySummaryAllRow, error) {
	row := q.db.QueryRow(ctx, getTelemetrySummaryAll, arg.FromTime, arg.ToTime)
	var i GetTelemetrySummaryAllRow
	err := row.Scan(
		&i.RequestCount,
		&i.TotalTokens,
		&i.TotalRequestedCostUsd,
		&i.TotalActualCostUsd,
		&i.TotalSavingsUsd,
	)
	return i, err
}

const getTelemetryTimeseriesDaily = `-- name: GetTelemetryTimeseriesDaily :many
SELECT
    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('day', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesDailyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryTimeseriesDailyRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd pgtype.Numeric
	ActualCostUsd    pgtype.Numeric
}

// Returns per-day cost buckets for the cost savings chart.
//
//	SELECT
//	    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('day', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesDaily(ctx context.Context, arg GetTelemetryTimeseriesDailyParams) ([]GetTelemetryTimeseriesDailyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesDaily, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesDailyRow
	for rows.Next() {
		var i GetTelemetryTimeseriesDailyRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesDailyAll = `-- name: GetTelemetryTimeseriesDailyAll :many
SELECT
    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('day', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesDailyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryTimeseriesDailyAllRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd pgtype.Numeric
	ActualCostUsd    pgtype.Numeric
}

// Per-day cost buckets across every installation. Admin-only.
//
//	SELECT
//	    date_trunc('day', timestamp)::timestamptz                                        AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('day', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesDailyAll(ctx context.Context, arg GetTelemetryTimeseriesDailyAllParams) ([]GetTelemetryTimeseriesDailyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesDailyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesDailyAllRow
	for rows.Next() {
		var i GetTelemetryTimeseriesDailyAllRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesHourly = `-- name: GetTelemetryTimeseriesHourly :many
SELECT
    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE installation_id = $1::uuid
  AND span_type = 'router.upstream'
  AND timestamp >= $2::timestamptz
  AND timestamp < $3::timestamptz
GROUP BY date_trunc('hour', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesHourlyParams struct {
	InstallationID uuid.UUID
	FromTime       pgtype.Timestamptz
	ToTime         pgtype.Timestamptz
}

type GetTelemetryTimeseriesHourlyRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd pgtype.Numeric
	ActualCostUsd    pgtype.Numeric
}

// Returns per-hour cost buckets for the cost savings chart.
//
//	SELECT
//	    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE installation_id = $1::uuid
//	  AND span_type = 'router.upstream'
//	  AND timestamp >= $2::timestamptz
//	  AND timestamp < $3::timestamptz
//	GROUP BY date_trunc('hour', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesHourly(ctx context.Context, arg GetTelemetryTimeseriesHourlyParams) ([]GetTelemetryTimeseriesHourlyRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesHourly, arg.InstallationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesHourlyRow
	for rows.Next() {
		var i GetTelemetryTimeseriesHourlyRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryTimeseriesHourlyAll = `-- name: GetTelemetryTimeseriesHourlyAll :many
SELECT
    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
FROM router.model_router_request_telemetry
WHERE span_type = 'router.upstream'
  AND timestamp >= $1::timestamptz
  AND timestamp < $2::timestamptz
GROUP BY date_trunc('hour', timestamp)
ORDER BY bucket ASC
`

type GetTelemetryTimeseriesHourlyAllParams struct {
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type GetTelemetryTimeseriesHourlyAllRow struct {
	Bucket           pgtype.Timestamptz
	RequestedCostUsd pgtype.Numeric
	ActualCostUsd    pgtype.Numeric
}

// Per-hour cost buckets across every installation. Admin-only.
//
//	SELECT
//	    date_trunc('hour', timestamp)::timestamptz                                       AS bucket,
//	    COALESCE(SUM(requested_input_cost_usd + requested_output_cost_usd), 0)::numeric AS requested_cost_usd,
//	    COALESCE(SUM(actual_input_cost_usd + actual_output_cost_usd), 0)::numeric       AS actual_cost_usd
//	FROM router.model_router_request_telemetry
//	WHERE span_type = 'router.upstream'
//	  AND timestamp >= $1::timestamptz
//	  AND timestamp < $2::timestamptz
//	GROUP BY date_trunc('hour', timestamp)
//	ORDER BY bucket ASC
func (q *Queries) GetTelemetryTimeseriesHourlyAll(ctx context.Context, arg GetTelemetryTimeseriesHourlyAllParams) ([]GetTelemetryTimeseriesHourlyAllRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTimeseriesHourlyAll, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTimeseriesHourlyAllRow
	for rows.Next() {
		var i GetTelemetryTimeseriesHourlyAllRow
		if err := rows.Scan(&i.Bucket, &i.RequestedCostUsd, &i.ActualCostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRequestTelemetry = `-- name: InsertRequestTelemetry :exec
INSERT INTO router.model_router_request_telemetry (
    installation_id,
    request_id,
    span_type,
    trace_id,
    timestamp,
    requested_model,
    decision_model,
    decision_provider,
    decision_reason,
    estimated_input_tokens,
    sticky_hit,
    embed_input,
    input_tokens,
    output_tokens,
    requested_input_cost_usd,
    requested_output_cost_usd,
    actual_input_cost_usd,
    actual_output_cost_usd,
    route_latency_ms,
    upstream_latency_ms,
    total_latency_ms,
    cross_format,
    upstream_status_code
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::timestamptz,
    $6::varchar,
    $7::varchar,
    $8::varchar,
    $9::varchar,
    $10::int,
    $11::boolean,
    $12::varchar,
    $13::int,
    $14::int,
    $15::numeric,
    $16::numeric,
    $17::numeric,
    $18::numeric,
    $19::bigint,
    $20::bigint,
    $21::bigint,
    $22::boolean,
    $23::int
)
ON CONFLICT (installation_id, request_id, span_type) DO NOTHING
`

type InsertRequestTelemetryParams struct {
	InstallationID         uuid.UUID
	RequestID              string
	SpanType               string
	TraceID                string
	Timestamp              pgtype.Timestamptz
	RequestedModel         string
	DecisionModel          string
	DecisionProvider       string
	DecisionReason         string
	EstimatedInputTokens   int32
	StickyHit              bool
	EmbedInput             string
	InputTokens            int32
	OutputTokens           int32
	RequestedInputCostUsd  pgtype.Numeric
	RequestedOutputCostUsd pgtype.Numeric
	ActualInputCostUsd     pgtype.Numeric
	ActualOutputCostUsd    pgtype.Numeric
	RouteLatencyMs         int64
	UpstreamLatencyMs      int64
	TotalLatencyMs         int64
	CrossFormat            bool
	UpstreamStatusCode     int32
}

// Records a completed proxied request for the dashboard UI.
//
//	INSERT INTO router.model_router_request_telemetry (
//	    installation_id,
//	    request_id,
//	    span_type,
//	    trace_id,
//	    timestamp,
//	    requested_model,
//	    decision_model,
//	    decision_provider,
//	    decision_reason,
//	    estimated_input_tokens,
//	    sticky_hit,
//	    embed_input,
//	    input_tokens,
//	    output_tokens,
//	    requested_input_cost_usd,
//	    requested_output_cost_usd,
//	    actual_input_cost_usd,
//	    actual_output_cost_usd,
//	    route_latency_ms,
//	    upstream_latency_ms,
//	    total_latency_ms,
//	    cross_format,
//	    upstream_status_code
//	) VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::timestamptz,
//	    $6::varchar,
//	    $7::varchar,
//	    $8::varchar,
//	    $9::varchar,
//	    $10::int,
//	    $11::boolean,
//	    $12::varchar,
//	    $13::int,
//	    $14::int,
//	    $15::numeric,
//	    $16::numeric,
//	    $17::numeric,
//	    $18::numeric,
//	    $19::bigint,
//	    $20::bigint,
//	    $21::bigint,
//	    $22::boolean,
//	    $23::int
//	)
//	ON CONFLICT (installation_id, request_id, span_type) DO NOTHING
func (q *Queries) InsertRequestTelemetry(ctx context.Context, arg InsertRequestTelemetryParams) error {
	_, err := q.db.Exec(ctx, insertRequestTelemetry,
		arg.InstallationID,
		arg.RequestID,
		arg.SpanType,
		arg.TraceID,
		arg.Timestamp,
		arg.RequestedModel,
		arg.DecisionModel,
		arg.DecisionProvider,
		arg.DecisionReason,
		arg.EstimatedInputTokens,
		arg.StickyHit,
		arg.EmbedInput,
		arg.InputTokens,
		arg.OutputTokens,
		arg.RequestedInputCostUsd,
		arg.RequestedOutputCostUsd,
		arg.ActualInputCostUsd,
		arg.ActualOutputCostUsd,
		arg.RouteLatencyMs,
		arg.UpstreamLatencyMs,
		arg.TotalLatencyMs,
		arg.CrossFormat,
		arg.UpstreamStatusCode,
	)
	return err
}
