// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_installations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createModelRouterInstallation = `-- name: CreateModelRouterInstallation :one
INSERT INTO router.model_router_installations (
    external_id,
    name,
    created_by,
    is_eval_allowlisted
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3,
    $4::boolean
)
RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, is_eval_allowlisted
`

type CreateModelRouterInstallationParams struct {
	ExternalID        string
	Name              string
	CreatedBy         *string
	IsEvalAllowlisted bool
}

// Creates a new model router installation.
//
//	INSERT INTO router.model_router_installations (
//	    external_id,
//	    name,
//	    created_by,
//	    is_eval_allowlisted
//	)
//	VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3,
//	    $4::boolean
//	)
//	RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, is_eval_allowlisted
func (q *Queries) CreateModelRouterInstallation(ctx context.Context, arg CreateModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, createModelRouterInstallation,
		arg.ExternalID,
		arg.Name,
		arg.CreatedBy,
		arg.IsEvalAllowlisted,
	)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.IsEvalAllowlisted,
	)
	return i, err
}

const getModelRouterInstallation = `-- name: GetModelRouterInstallation :one
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, is_eval_allowlisted
FROM router.model_router_installations
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type GetModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Gets an installation by id, scoped to an external_id to prevent cross-tenant access.
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, is_eval_allowlisted
//	FROM router.model_router_installations
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) GetModelRouterInstallation(ctx context.Context, arg GetModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, getModelRouterInstallation, arg.ID, arg.ExternalID)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.IsEvalAllowlisted,
	)
	return i, err
}

const listModelRouterInstallationsForExternalID = `-- name: ListModelRouterInstallationsForExternalID :many
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, is_eval_allowlisted
FROM router.model_router_installations
WHERE external_id = $1::varchar
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Lists active installations for an external_id.
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, is_eval_allowlisted
//	FROM router.model_router_installations
//	WHERE external_id = $1::varchar
//	  AND deleted_at IS NULL
//	ORDER BY created_at DESC
func (q *Queries) ListModelRouterInstallationsForExternalID(ctx context.Context, externalID string) ([]RouterModelRouterInstallation, error) {
	rows, err := q.db.Query(ctx, listModelRouterInstallationsForExternalID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterInstallation
	for rows.Next() {
		var i RouterModelRouterInstallation
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.IsEvalAllowlisted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setModelRouterInstallationEvalAllowlisted = `-- name: SetModelRouterInstallationEvalAllowlisted :exec
UPDATE router.model_router_installations
SET is_eval_allowlisted = $1::boolean,
    updated_at           = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type SetModelRouterInstallationEvalAllowlistedParams struct {
	IsEvalAllowlisted bool
	ID                uuid.UUID
	ExternalID        string
}

// Toggles the per-installation eval-override allowlist flag. Used by
// the eval harness seeding flow (seed-key with --eval-allowlist) to
// promote an installation without a redeploy. Scoped by
// external_id so a mismatched (external_id, installation) pair refuses to
// update instead of silently flipping a row in another tenant.
//
//	UPDATE router.model_router_installations
//	SET is_eval_allowlisted = $1::boolean,
//	    updated_at           = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SetModelRouterInstallationEvalAllowlisted(ctx context.Context, arg SetModelRouterInstallationEvalAllowlistedParams) error {
	_, err := q.db.Exec(ctx, setModelRouterInstallationEvalAllowlisted, arg.IsEvalAllowlisted, arg.ID, arg.ExternalID)
	return err
}

const softDeleteModelRouterInstallation = `-- name: SoftDeleteModelRouterInstallation :exec
UPDATE router.model_router_installations
SET deleted_at = NOW()
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type SoftDeleteModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Soft-deletes an installation, scoped to an external_id to prevent cross-tenant deletes.
//
//	UPDATE router.model_router_installations
//	SET deleted_at = NOW()
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteModelRouterInstallation(ctx context.Context, arg SoftDeleteModelRouterInstallationParams) error {
	_, err := q.db.Exec(ctx, softDeleteModelRouterInstallation, arg.ID, arg.ExternalID)
	return err
}
