// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policy_shadow_decisions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertPolicyShadowDecision = `-- name: InsertPolicyShadowDecision :exec
INSERT INTO router.policy_shadow_decisions (
    installation_id,
    organization_id,
    rollout_id,
    client_app,
    training_allowed,
    serving_strategy,
    serving_model,
    serving_provider,
    serving_route_id,
    serving_policy_route_key,
    serving_policy_artifact_id,
    serving_policy_artifact_sha256,
    shadow_strategy,
    shadow_model,
    shadow_provider,
    shadow_route_id,
    shadow_policy_route_key,
    shadow_policy_artifact_id,
    shadow_policy_artifact_sha256,
    shadow_latency_ms,
    shadow_error,
    models_agree
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::boolean,
    $6::varchar,
    $7::varchar,
    $8::varchar,
    $9::varchar,
    $10::varchar,
    $11::varchar,
    $12::varchar,
    $13::varchar,
    $14::varchar,
    $15::varchar,
    $16::varchar,
    $17::varchar,
    $18::varchar,
    $19::varchar,
    $20::bigint,
    $21::varchar,
    $22::boolean
)
`

type InsertPolicyShadowDecisionParams struct {
	InstallationID              uuid.UUID
	OrganizationID              *string
	RolloutID                   *string
	ClientApp                   *string
	TrainingAllowed             bool
	ServingStrategy             string
	ServingModel                string
	ServingProvider             string
	ServingRouteID              *string
	ServingPolicyRouteKey       *string
	ServingPolicyArtifactID     *string
	ServingPolicyArtifactSha256 *string
	ShadowStrategy              string
	ShadowModel                 *string
	ShadowProvider              *string
	ShadowRouteID               *string
	ShadowPolicyRouteKey        *string
	ShadowPolicyArtifactID      *string
	ShadowPolicyArtifactSha256  *string
	ShadowLatencyMs             int64
	ShadowError                 *string
	ModelsAgree                 bool
}

// InsertPolicyShadowDecision
//
//	INSERT INTO router.policy_shadow_decisions (
//	    installation_id,
//	    organization_id,
//	    rollout_id,
//	    client_app,
//	    training_allowed,
//	    serving_strategy,
//	    serving_model,
//	    serving_provider,
//	    serving_route_id,
//	    serving_policy_route_key,
//	    serving_policy_artifact_id,
//	    serving_policy_artifact_sha256,
//	    shadow_strategy,
//	    shadow_model,
//	    shadow_provider,
//	    shadow_route_id,
//	    shadow_policy_route_key,
//	    shadow_policy_artifact_id,
//	    shadow_policy_artifact_sha256,
//	    shadow_latency_ms,
//	    shadow_error,
//	    models_agree
//	) VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::boolean,
//	    $6::varchar,
//	    $7::varchar,
//	    $8::varchar,
//	    $9::varchar,
//	    $10::varchar,
//	    $11::varchar,
//	    $12::varchar,
//	    $13::varchar,
//	    $14::varchar,
//	    $15::varchar,
//	    $16::varchar,
//	    $17::varchar,
//	    $18::varchar,
//	    $19::varchar,
//	    $20::bigint,
//	    $21::varchar,
//	    $22::boolean
//	)
func (q *Queries) InsertPolicyShadowDecision(ctx context.Context, arg InsertPolicyShadowDecisionParams) error {
	_, err := q.db.Exec(ctx, insertPolicyShadowDecision,
		arg.InstallationID,
		arg.OrganizationID,
		arg.RolloutID,
		arg.ClientApp,
		arg.TrainingAllowed,
		arg.ServingStrategy,
		arg.ServingModel,
		arg.ServingProvider,
		arg.ServingRouteID,
		arg.ServingPolicyRouteKey,
		arg.ServingPolicyArtifactID,
		arg.ServingPolicyArtifactSha256,
		arg.ShadowStrategy,
		arg.ShadowModel,
		arg.ShadowProvider,
		arg.ShadowRouteID,
		arg.ShadowPolicyRouteKey,
		arg.ShadowPolicyArtifactID,
		arg.ShadowPolicyArtifactSha256,
		arg.ShadowLatencyMs,
		arg.ShadowError,
		arg.ModelsAgree,
	)
	return err
}
