// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_feedback.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestFeedback = `-- name: GetRequestFeedback :one
SELECT
    rating,
    comment
FROM router.request_feedback
WHERE installation_id = $1::uuid
  AND request_id = $2::varchar
`

type GetRequestFeedbackParams struct {
	InstallationID uuid.UUID
	RequestID      string
}

type GetRequestFeedbackRow struct {
	Rating  string
	Comment *string
}

// Read back one request's existing feedback for the feedback page so the user
// sees their prior rating. Returns sql.ErrNoRows when none exists yet.
//
//	SELECT
//	    rating,
//	    comment
//	FROM router.request_feedback
//	WHERE installation_id = $1::uuid
//	  AND request_id = $2::varchar
func (q *Queries) GetRequestFeedback(ctx context.Context, arg GetRequestFeedbackParams) (GetRequestFeedbackRow, error) {
	row := q.db.QueryRow(ctx, getRequestFeedback, arg.InstallationID, arg.RequestID)
	var i GetRequestFeedbackRow
	err := row.Scan(&i.Rating, &i.Comment)
	return i, err
}

const upsertRequestFeedback = `-- name: UpsertRequestFeedback :exec
INSERT INTO router.request_feedback (
    installation_id,
    external_id,
    request_id,
    rating,
    comment,
    source,
    router_user_id,
    updated_at
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    NULLIF($5::text, ''),
    $6::varchar,
    $7::uuid,
    NOW()
)
ON CONFLICT (installation_id, request_id) DO UPDATE SET
    rating = EXCLUDED.rating,
    comment = EXCLUDED.comment,
    source = EXCLUDED.source,
    router_user_id = EXCLUDED.router_user_id,
    updated_at = NOW()
`

type UpsertRequestFeedbackParams struct {
	InstallationID uuid.UUID
	ExternalID     string
	RequestID      string
	Rating         string
	Comment        *string
	Source         string
	RouterUserID   pgtype.UUID
}

// Upsert one request's feedback. The feedback link lets a user revise their
// rating (flip thumb or edit the comment), so a repeat submission for the same
// (installation, request) overwrites the prior row. Empty comments collapse to
// NULL so "" and "no comment" are indistinguishable downstream.
//
//	INSERT INTO router.request_feedback (
//	    installation_id,
//	    external_id,
//	    request_id,
//	    rating,
//	    comment,
//	    source,
//	    router_user_id,
//	    updated_at
//	) VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::varchar,
//	    NULLIF($5::text, ''),
//	    $6::varchar,
//	    $7::uuid,
//	    NOW()
//	)
//	ON CONFLICT (installation_id, request_id) DO UPDATE SET
//	    rating = EXCLUDED.rating,
//	    comment = EXCLUDED.comment,
//	    source = EXCLUDED.source,
//	    router_user_id = EXCLUDED.router_user_id,
//	    updated_at = NOW()
func (q *Queries) UpsertRequestFeedback(ctx context.Context, arg UpsertRequestFeedbackParams) error {
	_, err := q.db.Exec(ctx, upsertRequestFeedback,
		arg.InstallationID,
		arg.ExternalID,
		arg.RequestID,
		arg.Rating,
		arg.Comment,
		arg.Source,
		arg.RouterUserID,
	)
	return err
}
