// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: router_feedback.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertRouterFeedback = `-- name: InsertRouterFeedback :exec
INSERT INTO router.router_feedback (
    installation_id,
    session_key,
    role,
    router_user_id,
    client_app,
    session_id,
    requested_model,
    served_model,
    feedback,
    rating,
    suggested_label,
    source
) VALUES (
    $1::uuid,
    $2::bytea,
    $3::varchar,
    $4::uuid,
    $5::text,
    $6::varchar,
    $7::varchar,
    $8::varchar,
    $9::text,
    $10::varchar,
    $11::varchar,
    $12::varchar
)
`

type InsertRouterFeedbackParams struct {
	InstallationID uuid.UUID
	SessionKey     []byte
	Role           string
	RouterUserID   pgtype.UUID
	ClientApp      *string
	SessionID      *string
	RequestedModel string
	ServedModel    string
	Feedback       string
	Rating         *string
	SuggestedLabel *string
	Source         string
}

// Records one /router-feedback submission. Written with
// context.Background() (the synthetic ack response may already have been
// flushed and the request ctx canceled). served_model is the session pin's
// LastServedModel at submission time; empty when the session had no pin.
//
//	INSERT INTO router.router_feedback (
//	    installation_id,
//	    session_key,
//	    role,
//	    router_user_id,
//	    client_app,
//	    session_id,
//	    requested_model,
//	    served_model,
//	    feedback,
//	    rating,
//	    suggested_label,
//	    source
//	) VALUES (
//	    $1::uuid,
//	    $2::bytea,
//	    $3::varchar,
//	    $4::uuid,
//	    $5::text,
//	    $6::varchar,
//	    $7::varchar,
//	    $8::varchar,
//	    $9::text,
//	    $10::varchar,
//	    $11::varchar,
//	    $12::varchar
//	)
func (q *Queries) InsertRouterFeedback(ctx context.Context, arg InsertRouterFeedbackParams) error {
	_, err := q.db.Exec(ctx, insertRouterFeedback,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.RouterUserID,
		arg.ClientApp,
		arg.SessionID,
		arg.RequestedModel,
		arg.ServedModel,
		arg.Feedback,
		arg.Rating,
		arg.SuggestedLabel,
		arg.Source,
	)
	return err
}
