// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_pins.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionPin = `-- name: GetSessionPin :one
SELECT session_key, role, installation_id, pinned_provider, pinned_model, decision_reason, turn_count, pinned_until, first_pinned_at, last_seen_at, last_input_tokens, last_cached_read_tokens, last_cached_write_tokens, last_output_tokens, last_turn_ended_at, consecutive_upstream_errors, last_served_model, has_ever_switched, trajectory_id, parent_trajectory_id, cache_ledger, cumulative_spend_microusd, switch_count
FROM router.session_pins
WHERE session_key = $1::bytea
  AND role        = $2::varchar
`

type GetSessionPinParams struct {
	SessionKey []byte
	Role       string
}

// Reads the active pin for a (session_key, role) pair. Single-row;
// returns sql.ErrNoRows when no pin is recorded yet. The caller checks
// pinned_until against now() to discard expired rows that the hourly
// sweep hasn't collected yet. The last_* token columns and
// last_turn_ended_at carry the previous turn's upstream usage; the
// planner reads them to weigh switch EV against eviction cost.
//
//	SELECT session_key, role, installation_id, pinned_provider, pinned_model, decision_reason, turn_count, pinned_until, first_pinned_at, last_seen_at, last_input_tokens, last_cached_read_tokens, last_cached_write_tokens, last_output_tokens, last_turn_ended_at, consecutive_upstream_errors, last_served_model, has_ever_switched, trajectory_id, parent_trajectory_id, cache_ledger, cumulative_spend_microusd, switch_count
//	FROM router.session_pins
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
func (q *Queries) GetSessionPin(ctx context.Context, arg GetSessionPinParams) (RouterSessionPin, error) {
	row := q.db.QueryRow(ctx, getSessionPin, arg.SessionKey, arg.Role)
	var i RouterSessionPin
	err := row.Scan(
		&i.SessionKey,
		&i.Role,
		&i.InstallationID,
		&i.PinnedProvider,
		&i.PinnedModel,
		&i.DecisionReason,
		&i.TurnCount,
		&i.PinnedUntil,
		&i.FirstPinnedAt,
		&i.LastSeenAt,
		&i.LastInputTokens,
		&i.LastCachedReadTokens,
		&i.LastCachedWriteTokens,
		&i.LastOutputTokens,
		&i.LastTurnEndedAt,
		&i.ConsecutiveUpstreamErrors,
		&i.LastServedModel,
		&i.HasEverSwitched,
		&i.TrajectoryID,
		&i.ParentTrajectoryID,
		&i.CacheLedger,
		&i.CumulativeSpendMicrousd,
		&i.SwitchCount,
	)
	return i, err
}

const incrementSessionPinUpstreamErrors = `-- name: IncrementSessionPinUpstreamErrors :one
UPDATE router.session_pins
SET consecutive_upstream_errors = consecutive_upstream_errors + 1
WHERE session_key = $1::bytea
  AND role        = $2::varchar
RETURNING consecutive_upstream_errors
`

type IncrementSessionPinUpstreamErrorsParams struct {
	SessionKey []byte
	Role       string
}

// Atomically increments consecutive_upstream_errors and returns the
// new value. The turn loop calls this after a non-retryable upstream
// 4xx on a sticky-pinned turn; the returned count drives the
// two-strike eviction decision. Returns sql.ErrNoRows if no pin
// exists, which the adapter maps to a no-op (pin must already be
// evicted by another path, e.g. force-model / loop-break).
//
//	UPDATE router.session_pins
//	SET consecutive_upstream_errors = consecutive_upstream_errors + 1
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
//	RETURNING consecutive_upstream_errors
func (q *Queries) IncrementSessionPinUpstreamErrors(ctx context.Context, arg IncrementSessionPinUpstreamErrorsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementSessionPinUpstreamErrors, arg.SessionKey, arg.Role)
	var consecutive_upstream_errors int32
	err := row.Scan(&consecutive_upstream_errors)
	return consecutive_upstream_errors, err
}

const resetSessionPinUpstreamErrors = `-- name: ResetSessionPinUpstreamErrors :exec
UPDATE router.session_pins
SET consecutive_upstream_errors = 0
WHERE session_key = $1::bytea
  AND role        = $2::varchar
  AND consecutive_upstream_errors > 0
`

type ResetSessionPinUpstreamErrorsParams struct {
	SessionKey []byte
	Role       string
}

// Clears the two-strike counter after a successful turn. UPDATE
// matches by (session_key, role); zero rows affected on missing pin
// is a successful no-op like UpdateSessionPinUsage.
//
//	UPDATE router.session_pins
//	SET consecutive_upstream_errors = 0
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
//	  AND consecutive_upstream_errors > 0
func (q *Queries) ResetSessionPinUpstreamErrors(ctx context.Context, arg ResetSessionPinUpstreamErrorsParams) error {
	_, err := q.db.Exec(ctx, resetSessionPinUpstreamErrors, arg.SessionKey, arg.Role)
	return err
}

const sweepExpiredSessionPins = `-- name: SweepExpiredSessionPins :exec
DELETE FROM router.session_pins
WHERE pinned_until < now() - interval '24 hours'
`

// Garbage-collects pins that have been expired for >24h. The 24h grace
// means a transient Postgres outage doesn't immediately prune live pins;
// the hourly sweep is bounded because the row count is one per active
// session.
//
//	DELETE FROM router.session_pins
//	WHERE pinned_until < now() - interval '24 hours'
func (q *Queries) SweepExpiredSessionPins(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepExpiredSessionPins)
	return err
}

const updateSessionPinUsage = `-- name: UpdateSessionPinUsage :exec
UPDATE router.session_pins
SET last_input_tokens        = $1::int,
    last_cached_read_tokens  = $2::int,
    last_cached_write_tokens = $3::int,
    last_output_tokens       = $4::int,
    last_turn_ended_at       = $5::timestamptz,
    has_ever_switched        = has_ever_switched
      OR (last_served_model <> '' AND last_served_model <> $6::varchar),
    switch_count             = switch_count
      + CASE WHEN last_served_model <> '' AND last_served_model <> $6::varchar
          THEN 1 ELSE 0 END,
    cumulative_spend_microusd = cumulative_spend_microusd + $7::bigint,
    cache_ledger             = jsonb_set(
      cache_ledger,
      ARRAY[$8::text],
      jsonb_build_object(
        'last_turn_at',               to_jsonb($5::timestamptz),
        'last_input_tokens',          $1::int,
        'last_cache_read_tokens',     $2::int,
        'last_cache_creation_tokens', $3::int,
        'last_output_tokens',         $4::int,
        'consecutive_turns', CASE
          WHEN last_served_model = $6::varchar
            THEN COALESCE((cache_ledger->($8::text)->>'consecutive_turns')::int, 0) + 1
          ELSE 1
        END,
        'last_reconcile_error_tokens', CASE
          WHEN jsonb_exists(cache_ledger, $8::text)
            THEN to_jsonb(($2::int)
              - COALESCE((cache_ledger->($8::text)->>'last_input_tokens')::int, 0))
          ELSE 'null'::jsonb
        END
      )
    ),
    last_served_model        = $6::varchar
WHERE session_key = $9::bytea
  AND role        = $10::varchar
`

type UpdateSessionPinUsageParams struct {
	LastInputTokens       int32
	LastCachedReadTokens  int32
	LastCachedWriteTokens int32
	LastOutputTokens      int32
	LastTurnEndedAt       pgtype.Timestamptz
	LastServedModel       string
	TurnSpendMicrousd     int64
	LedgerKey             string
	SessionKey            []byte
	Role                  string
}

// Records the previous turn's upstream token usage on an existing pin
// row. Fired off the request path after the upstream response
// completes; the planner reads these columns at the start of the next
// turn to compute switch EV against eviction cost. The UPDATE matches
// by (session_key, role); if the pin has been evicted or never
// existed, zero rows are affected and the adapter wraps that as a
// successful no-op. last_served_model records the model that actually
// served this turn; it lives here (not in UpsertSessionPin) so a
// /force-model upsert cannot overwrite the genuinely-last-served model
// before the next turn reads it to detect a mid-session model switch.
// has_ever_switched latches true the first time the just-served model
// differs from a prior non-empty last_served_model. ModelSwitched (derived
// from last_served_model) strips stale Anthropic thinking-block signatures
// only on the single transition turn, but Claude Code re-sends its full
// transcript every turn, so once a session has switched at all, the latch
// keeps the emit path stripping on every subsequent same-model turn for the
// session's life — the only window in which those poisoned blocks would
// otherwise reach Anthropic and 400.
// The cache_ledger merge upserts this turn's (provider, model) entry in the
// same atomic UPDATE: consecutive_turns increments while the served model is
// unchanged and resets to 1 on a switch; last_reconcile_error_tokens records,
// on revisit of an existing entry, the signed gap between the cache reuse the
// entry predicted (its previous last_input_tokens) and the cache_read the
// provider actually reported — a learnable provider-cache-reliability signal.
// switch_count and cumulative_spend_microusd are session aggregates for the
// step record. Entry count is bounded by roster size + pin TTL; no LRU trim.
//
//	UPDATE router.session_pins
//	SET last_input_tokens        = $1::int,
//	    last_cached_read_tokens  = $2::int,
//	    last_cached_write_tokens = $3::int,
//	    last_output_tokens       = $4::int,
//	    last_turn_ended_at       = $5::timestamptz,
//	    has_ever_switched        = has_ever_switched
//	      OR (last_served_model <> '' AND last_served_model <> $6::varchar),
//	    switch_count             = switch_count
//	      + CASE WHEN last_served_model <> '' AND last_served_model <> $6::varchar
//	          THEN 1 ELSE 0 END,
//	    cumulative_spend_microusd = cumulative_spend_microusd + $7::bigint,
//	    cache_ledger             = jsonb_set(
//	      cache_ledger,
//	      ARRAY[$8::text],
//	      jsonb_build_object(
//	        'last_turn_at',               to_jsonb($5::timestamptz),
//	        'last_input_tokens',          $1::int,
//	        'last_cache_read_tokens',     $2::int,
//	        'last_cache_creation_tokens', $3::int,
//	        'last_output_tokens',         $4::int,
//	        'consecutive_turns', CASE
//	          WHEN last_served_model = $6::varchar
//	            THEN COALESCE((cache_ledger->($8::text)->>'consecutive_turns')::int, 0) + 1
//	          ELSE 1
//	        END,
//	        'last_reconcile_error_tokens', CASE
//	          WHEN jsonb_exists(cache_ledger, $8::text)
//	            THEN to_jsonb(($2::int)
//	              - COALESCE((cache_ledger->($8::text)->>'last_input_tokens')::int, 0))
//	          ELSE 'null'::jsonb
//	        END
//	      )
//	    ),
//	    last_served_model        = $6::varchar
//	WHERE session_key = $9::bytea
//	  AND role        = $10::varchar
func (q *Queries) UpdateSessionPinUsage(ctx context.Context, arg UpdateSessionPinUsageParams) error {
	_, err := q.db.Exec(ctx, updateSessionPinUsage,
		arg.LastInputTokens,
		arg.LastCachedReadTokens,
		arg.LastCachedWriteTokens,
		arg.LastOutputTokens,
		arg.LastTurnEndedAt,
		arg.LastServedModel,
		arg.TurnSpendMicrousd,
		arg.LedgerKey,
		arg.SessionKey,
		arg.Role,
	)
	return err
}

const upsertSessionPin = `-- name: UpsertSessionPin :exec
INSERT INTO router.session_pins (
  session_key, role, installation_id, pinned_provider,
  pinned_model, decision_reason, turn_count, pinned_until
) VALUES (
  $1::bytea, $2::varchar, $3::uuid,
  $4::varchar, $5::varchar,
  $6::text, $7::int, $8::timestamp
)
ON CONFLICT (session_key, role) DO UPDATE SET
  pinned_provider = EXCLUDED.pinned_provider,
  pinned_model    = EXCLUDED.pinned_model,
  decision_reason = EXCLUDED.decision_reason,
  turn_count      = router.session_pins.turn_count + 1,
  pinned_until    = EXCLUDED.pinned_until,
  last_seen_at    = CURRENT_TIMESTAMP,
  consecutive_upstream_errors = CASE
    WHEN router.session_pins.pinned_model = EXCLUDED.pinned_model
      THEN router.session_pins.consecutive_upstream_errors
    ELSE 0
  END
`

type UpsertSessionPinParams struct {
	SessionKey     []byte
	Role           string
	InstallationID uuid.UUID
	PinnedProvider string
	PinnedModel    string
	DecisionReason string
	TurnCount      int32
	PinnedUntil    pgtype.Timestamp
}

// Upserts a pin, refreshing pinned_until on every hit (sliding TTL).
// turn_count increments on conflict so we can observe how many turns a
// single (session_key, role) lives for. installation_id is set on first
// insert and not touched on update — re-binding a session to a different
// installation would indicate a bug, not a legitimate state. The
// last_*_tokens / last_turn_ended_at columns are deliberately omitted
// from the ON CONFLICT update set: only UpdateSessionPinUsage writes
// them, so the at-start-of-turn refresh here cannot clobber the
// previous turn's usage with zeros before the planner reads it.
//
// consecutive_upstream_errors is preserved on a same-model refresh (so
// the two-strike eviction counter accumulates across turns of the same
// sticky pin) but reset to 0 on a switch (different model = clean
// slate). The reset on switch also covers the loop-break / force-model
// pin-expiry writes, which set pinned_model to the empty string.
//
//	INSERT INTO router.session_pins (
//	  session_key, role, installation_id, pinned_provider,
//	  pinned_model, decision_reason, turn_count, pinned_until
//	) VALUES (
//	  $1::bytea, $2::varchar, $3::uuid,
//	  $4::varchar, $5::varchar,
//	  $6::text, $7::int, $8::timestamp
//	)
//	ON CONFLICT (session_key, role) DO UPDATE SET
//	  pinned_provider = EXCLUDED.pinned_provider,
//	  pinned_model    = EXCLUDED.pinned_model,
//	  decision_reason = EXCLUDED.decision_reason,
//	  turn_count      = router.session_pins.turn_count + 1,
//	  pinned_until    = EXCLUDED.pinned_until,
//	  last_seen_at    = CURRENT_TIMESTAMP,
//	  consecutive_upstream_errors = CASE
//	    WHEN router.session_pins.pinned_model = EXCLUDED.pinned_model
//	      THEN router.session_pins.consecutive_upstream_errors
//	    ELSE 0
//	  END
func (q *Queries) UpsertSessionPin(ctx context.Context, arg UpsertSessionPinParams) error {
	_, err := q.db.Exec(ctx, upsertSessionPin,
		arg.SessionKey,
		arg.Role,
		arg.InstallationID,
		arg.PinnedProvider,
		arg.PinnedModel,
		arg.DecisionReason,
		arg.TurnCount,
		arg.PinnedUntil,
	)
	return err
}
