// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_pins.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionPin = `-- name: GetSessionPin :one
SELECT session_key, role, installation_id, pinned_provider, pinned_model, decision_reason, turn_count, pinned_until, first_pinned_at, last_seen_at
FROM router.session_pins
WHERE session_key = $1::bytea
  AND role        = $2::varchar
`

type GetSessionPinParams struct {
	SessionKey []byte
	Role       string
}

// Reads the active pin for a (session_key, role) pair. Single-row;
// returns sql.ErrNoRows when no pin is recorded yet. The caller checks
// pinned_until against now() to discard expired rows that the hourly
// sweep hasn't collected yet.
//
//	SELECT session_key, role, installation_id, pinned_provider, pinned_model, decision_reason, turn_count, pinned_until, first_pinned_at, last_seen_at
//	FROM router.session_pins
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
func (q *Queries) GetSessionPin(ctx context.Context, arg GetSessionPinParams) (RouterSessionPin, error) {
	row := q.db.QueryRow(ctx, getSessionPin, arg.SessionKey, arg.Role)
	var i RouterSessionPin
	err := row.Scan(
		&i.SessionKey,
		&i.Role,
		&i.InstallationID,
		&i.PinnedProvider,
		&i.PinnedModel,
		&i.DecisionReason,
		&i.TurnCount,
		&i.PinnedUntil,
		&i.FirstPinnedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const sweepExpiredSessionPins = `-- name: SweepExpiredSessionPins :exec
DELETE FROM router.session_pins
WHERE pinned_until < now() - interval '24 hours'
`

// Garbage-collects pins that have been expired for >24h. The 24h grace
// means a transient Postgres outage doesn't immediately prune live pins;
// the hourly sweep is bounded because the row count is one per active
// session.
//
//	DELETE FROM router.session_pins
//	WHERE pinned_until < now() - interval '24 hours'
func (q *Queries) SweepExpiredSessionPins(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepExpiredSessionPins)
	return err
}

const upsertSessionPin = `-- name: UpsertSessionPin :exec
INSERT INTO router.session_pins (
  session_key, role, installation_id, pinned_provider,
  pinned_model, decision_reason, turn_count, pinned_until
) VALUES (
  $1::bytea, $2::varchar, $3::uuid,
  $4::varchar, $5::varchar,
  $6::text, $7::int, $8::timestamp
)
ON CONFLICT (session_key, role) DO UPDATE SET
  pinned_provider = EXCLUDED.pinned_provider,
  pinned_model    = EXCLUDED.pinned_model,
  decision_reason = EXCLUDED.decision_reason,
  turn_count      = router.session_pins.turn_count + 1,
  pinned_until    = EXCLUDED.pinned_until,
  last_seen_at    = CURRENT_TIMESTAMP
`

type UpsertSessionPinParams struct {
	SessionKey     []byte
	Role           string
	InstallationID uuid.UUID
	PinnedProvider string
	PinnedModel    string
	DecisionReason string
	TurnCount      int32
	PinnedUntil    pgtype.Timestamp
}

// Upserts a pin, refreshing pinned_until on every hit (sliding TTL).
// turn_count increments on conflict so we can observe how many turns a
// single (session_key, role) lives for. installation_id is set on first
// insert and not touched on update — re-binding a session to a different
// installation would indicate a bug, not a legitimate state.
//
//	INSERT INTO router.session_pins (
//	  session_key, role, installation_id, pinned_provider,
//	  pinned_model, decision_reason, turn_count, pinned_until
//	) VALUES (
//	  $1::bytea, $2::varchar, $3::uuid,
//	  $4::varchar, $5::varchar,
//	  $6::text, $7::int, $8::timestamp
//	)
//	ON CONFLICT (session_key, role) DO UPDATE SET
//	  pinned_provider = EXCLUDED.pinned_provider,
//	  pinned_model    = EXCLUDED.pinned_model,
//	  decision_reason = EXCLUDED.decision_reason,
//	  turn_count      = router.session_pins.turn_count + 1,
//	  pinned_until    = EXCLUDED.pinned_until,
//	  last_seen_at    = CURRENT_TIMESTAMP
func (q *Queries) UpsertSessionPin(ctx context.Context, arg UpsertSessionPinParams) error {
	_, err := q.db.Exec(ctx, upsertSessionPin,
		arg.SessionKey,
		arg.Role,
		arg.InstallationID,
		arg.PinnedProvider,
		arg.PinnedModel,
		arg.DecisionReason,
		arg.TurnCount,
		arg.PinnedUntil,
	)
	return err
}
