// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spend_reservations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decrementAPIKeyReserved = `-- name: DecrementAPIKeyReserved :exec
UPDATE router.model_router_api_keys
SET reserved_usd_micros = GREATEST(0, reserved_usd_micros - $1::bigint)
WHERE id = $2::uuid
`

type DecrementAPIKeyReservedParams struct {
	AmountUsdMicros int64
	APIKeyID        uuid.UUID
}

// DecrementAPIKeyReserved
//
//	UPDATE router.model_router_api_keys
//	SET reserved_usd_micros = GREATEST(0, reserved_usd_micros - $1::bigint)
//	WHERE id = $2::uuid
func (q *Queries) DecrementAPIKeyReserved(ctx context.Context, arg DecrementAPIKeyReservedParams) error {
	_, err := q.db.Exec(ctx, decrementAPIKeyReserved, arg.AmountUsdMicros, arg.APIKeyID)
	return err
}

const decrementOrgMonthReserved = `-- name: DecrementOrgMonthReserved :exec
UPDATE router.organization_monthly_spend
SET reserved_usd_micros = GREATEST(0, reserved_usd_micros - $1::bigint),
    updated_at = NOW()
WHERE organization_id = $2::varchar
  AND month = $3::date
`

type DecrementOrgMonthReservedParams struct {
	AmountUsdMicros int64
	OrganizationID  string
	Month           pgtype.Date
}

// DecrementOrgMonthReserved
//
//	UPDATE router.organization_monthly_spend
//	SET reserved_usd_micros = GREATEST(0, reserved_usd_micros - $1::bigint),
//	    updated_at = NOW()
//	WHERE organization_id = $2::varchar
//	  AND month = $3::date
func (q *Queries) DecrementOrgMonthReserved(ctx context.Context, arg DecrementOrgMonthReservedParams) error {
	_, err := q.db.Exec(ctx, decrementOrgMonthReserved, arg.AmountUsdMicros, arg.OrganizationID, arg.Month)
	return err
}

const decrementUserMonthReserved = `-- name: DecrementUserMonthReserved :exec
UPDATE router.model_router_user_monthly_spend
SET reserved_usd_micros = GREATEST(0, reserved_usd_micros - $1::bigint),
    updated_at = NOW()
WHERE router_user_id = $2::uuid
  AND month = $3::date
`

type DecrementUserMonthReservedParams struct {
	AmountUsdMicros int64
	RouterUserID    uuid.UUID
	Month           pgtype.Date
}

// DecrementUserMonthReserved
//
//	UPDATE router.model_router_user_monthly_spend
//	SET reserved_usd_micros = GREATEST(0, reserved_usd_micros - $1::bigint),
//	    updated_at = NOW()
//	WHERE router_user_id = $2::uuid
//	  AND month = $3::date
func (q *Queries) DecrementUserMonthReserved(ctx context.Context, arg DecrementUserMonthReservedParams) error {
	_, err := q.db.Exec(ctx, decrementUserMonthReserved, arg.AmountUsdMicros, arg.RouterUserID, arg.Month)
	return err
}

const deleteExpiredSpendReservations = `-- name: DeleteExpiredSpendReservations :many
DELETE FROM router.spend_reservations
WHERE expires_at < $1::timestamptz
RETURNING id, scope_kind, scope_id, month, amount_usd_micros
`

type DeleteExpiredSpendReservationsRow struct {
	ID              uuid.UUID
	ScopeKind       string
	ScopeID         string
	Month           pgtype.Date
	AmountUsdMicros int64
}

// Deletes every expired reservation and returns the doomed rows so the
// adapter can decrement denormalized reserved counters. Prefer calling
// DeleteSpendReservation per id from Go when settling a known hold; this
// batch path is for the TTL sweeper only.
//
//	DELETE FROM router.spend_reservations
//	WHERE expires_at < $1::timestamptz
//	RETURNING id, scope_kind, scope_id, month, amount_usd_micros
func (q *Queries) DeleteExpiredSpendReservations(ctx context.Context, now pgtype.Timestamptz) ([]DeleteExpiredSpendReservationsRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredSpendReservations, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteExpiredSpendReservationsRow
	for rows.Next() {
		var i DeleteExpiredSpendReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Month,
			&i.AmountUsdMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSpendReservation = `-- name: DeleteSpendReservation :one
DELETE FROM router.spend_reservations
WHERE id = $1::uuid
RETURNING id, scope_kind, scope_id, month, amount_usd_micros
`

type DeleteSpendReservationRow struct {
	ID              uuid.UUID
	ScopeKind       string
	ScopeID         string
	Month           pgtype.Date
	AmountUsdMicros int64
}

// Atomic consume: DELETE … RETURNING is the sole settle/release/sweep
// primitive. Zero rows = already released/settled/swept (idempotent no-op).
//
//	DELETE FROM router.spend_reservations
//	WHERE id = $1::uuid
//	RETURNING id, scope_kind, scope_id, month, amount_usd_micros
func (q *Queries) DeleteSpendReservation(ctx context.Context, id uuid.UUID) (DeleteSpendReservationRow, error) {
	row := q.db.QueryRow(ctx, deleteSpendReservation, id)
	var i DeleteSpendReservationRow
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Month,
		&i.AmountUsdMicros,
	)
	return i, err
}

const ensureOrgMonthlySpendRow = `-- name: EnsureOrgMonthlySpendRow :exec
INSERT INTO router.organization_monthly_spend (organization_id, month, spent_usd_micros, reserved_usd_micros)
VALUES (
    $1::varchar,
    DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date,
    0,
    0
)
ON CONFLICT (organization_id, month) DO NOTHING
`

// Ensures the current UTC-month org spend row exists so a reserve UPDATE can
// target it. No-op when the row is already present.
//
//	INSERT INTO router.organization_monthly_spend (organization_id, month, spent_usd_micros, reserved_usd_micros)
//	VALUES (
//	    $1::varchar,
//	    DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date,
//	    0,
//	    0
//	)
//	ON CONFLICT (organization_id, month) DO NOTHING
func (q *Queries) EnsureOrgMonthlySpendRow(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, ensureOrgMonthlySpendRow, organizationID)
	return err
}

const ensureUserMonthlySpendRow = `-- name: EnsureUserMonthlySpendRow :exec
INSERT INTO router.model_router_user_monthly_spend (router_user_id, month, spent_usd_micros, reserved_usd_micros)
VALUES (
    $1::uuid,
    DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date,
    0,
    0
)
ON CONFLICT (router_user_id, month) DO NOTHING
`

// EnsureUserMonthlySpendRow
//
//	INSERT INTO router.model_router_user_monthly_spend (router_user_id, month, spent_usd_micros, reserved_usd_micros)
//	VALUES (
//	    $1::uuid,
//	    DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date,
//	    0,
//	    0
//	)
//	ON CONFLICT (router_user_id, month) DO NOTHING
func (q *Queries) EnsureUserMonthlySpendRow(ctx context.Context, routerUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureUserMonthlySpendRow, routerUserID)
	return err
}

const insertSpendReservation = `-- name: InsertSpendReservation :one
INSERT INTO router.spend_reservations (
    scope_kind,
    scope_id,
    month,
    amount_usd_micros,
    expires_at,
    router_request_id
) VALUES (
    $1::varchar,
    $2::varchar,
    $3::date,
    $4::bigint,
    $5::timestamptz,
    $6::varchar
)
RETURNING id, scope_kind, scope_id, month, amount_usd_micros, expires_at
`

type InsertSpendReservationParams struct {
	ScopeKind       string
	ScopeID         string
	Month           pgtype.Date
	AmountUsdMicros int64
	ExpiresAt       pgtype.Timestamptz
	RouterRequestID *string
}

type InsertSpendReservationRow struct {
	ID              uuid.UUID
	ScopeKind       string
	ScopeID         string
	Month           pgtype.Date
	AmountUsdMicros int64
	ExpiresAt       pgtype.Timestamptz
}

// InsertSpendReservation
//
//	INSERT INTO router.spend_reservations (
//	    scope_kind,
//	    scope_id,
//	    month,
//	    amount_usd_micros,
//	    expires_at,
//	    router_request_id
//	) VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3::date,
//	    $4::bigint,
//	    $5::timestamptz,
//	    $6::varchar
//	)
//	RETURNING id, scope_kind, scope_id, month, amount_usd_micros, expires_at
func (q *Queries) InsertSpendReservation(ctx context.Context, arg InsertSpendReservationParams) (InsertSpendReservationRow, error) {
	row := q.db.QueryRow(ctx, insertSpendReservation,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Month,
		arg.AmountUsdMicros,
		arg.ExpiresAt,
		arg.RouterRequestID,
	)
	var i InsertSpendReservationRow
	err := row.Scan(
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Month,
		&i.AmountUsdMicros,
		&i.ExpiresAt,
	)
	return i, err
}

const tryBumpAPIKeyReserved = `-- name: TryBumpAPIKeyReserved :one
UPDATE router.model_router_api_keys k
SET reserved_usd_micros = k.reserved_usd_micros + $1::bigint
WHERE k.id = $2::uuid
  AND k.deleted_at IS NULL
  AND k.spend_cap_usd_micros IS NOT NULL
  AND k.spent_usd_micros + k.reserved_usd_micros + $1::bigint
      <= k.spend_cap_usd_micros
RETURNING k.id
`

type TryBumpAPIKeyReservedParams struct {
	AmountUsdMicros int64
	APIKeyID        uuid.UUID
}

// Bumps api-key lifetime reserved under the key's spend_cap. Zero rows when
// the key is missing, uncapped, or the bump would exceed the cap.
//
//	UPDATE router.model_router_api_keys k
//	SET reserved_usd_micros = k.reserved_usd_micros + $1::bigint
//	WHERE k.id = $2::uuid
//	  AND k.deleted_at IS NULL
//	  AND k.spend_cap_usd_micros IS NOT NULL
//	  AND k.spent_usd_micros + k.reserved_usd_micros + $1::bigint
//	      <= k.spend_cap_usd_micros
//	RETURNING k.id
func (q *Queries) TryBumpAPIKeyReserved(ctx context.Context, arg TryBumpAPIKeyReservedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, tryBumpAPIKeyReserved, arg.AmountUsdMicros, arg.APIKeyID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const tryBumpOrgMonthReserved = `-- name: TryBumpOrgMonthReserved :one
UPDATE router.organization_monthly_spend sp
SET reserved_usd_micros = sp.reserved_usd_micros + $1::bigint,
    updated_at = NOW()
FROM router.organization_spend_limits lim
WHERE sp.organization_id = $2::varchar
  AND sp.month = DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date
  AND lim.organization_id = sp.organization_id
  AND lim.org_monthly_limit_usd_micros IS NOT NULL
  AND sp.spent_usd_micros + sp.reserved_usd_micros + $1::bigint
      <= lim.org_monthly_limit_usd_micros
RETURNING sp.organization_id
`

type TryBumpOrgMonthReservedParams struct {
	AmountUsdMicros int64
	OrganizationID  string
}

// Atomically bumps org-month reserved when spent+reserved+amount still fits
// under the configured org monthly limit. Returns the organization_id on
// success; zero rows means limit reached (or no limit configured — caller
// must skip reserve when limit is NULL before calling this).
//
//	UPDATE router.organization_monthly_spend sp
//	SET reserved_usd_micros = sp.reserved_usd_micros + $1::bigint,
//	    updated_at = NOW()
//	FROM router.organization_spend_limits lim
//	WHERE sp.organization_id = $2::varchar
//	  AND sp.month = DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date
//	  AND lim.organization_id = sp.organization_id
//	  AND lim.org_monthly_limit_usd_micros IS NOT NULL
//	  AND sp.spent_usd_micros + sp.reserved_usd_micros + $1::bigint
//	      <= lim.org_monthly_limit_usd_micros
//	RETURNING sp.organization_id
func (q *Queries) TryBumpOrgMonthReserved(ctx context.Context, arg TryBumpOrgMonthReservedParams) (string, error) {
	row := q.db.QueryRow(ctx, tryBumpOrgMonthReserved, arg.AmountUsdMicros, arg.OrganizationID)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}

const tryBumpUserMonthReserved = `-- name: TryBumpUserMonthReserved :one
UPDATE router.model_router_user_monthly_spend sp
SET reserved_usd_micros = sp.reserved_usd_micros + $1::bigint,
    updated_at = NOW()
WHERE sp.router_user_id = $2::uuid
  AND sp.month = DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date
  AND sp.spent_usd_micros + sp.reserved_usd_micros + $1::bigint
      <= $3::bigint
RETURNING sp.router_user_id
`

type TryBumpUserMonthReservedParams struct {
	AmountUsdMicros int64
	RouterUserID    uuid.UUID
	LimitUsdMicros  int64
}

// Bumps user-month reserved under the effective limit (per-user override when
// present, else org default). Caller supplies the already-resolved effective
// limit; NULL limit means the caller should skip this scope.
//
//	UPDATE router.model_router_user_monthly_spend sp
//	SET reserved_usd_micros = sp.reserved_usd_micros + $1::bigint,
//	    updated_at = NOW()
//	WHERE sp.router_user_id = $2::uuid
//	  AND sp.month = DATE_TRUNC('month', NOW() AT TIME ZONE 'utc')::date
//	  AND sp.spent_usd_micros + sp.reserved_usd_micros + $1::bigint
//	      <= $3::bigint
//	RETURNING sp.router_user_id
func (q *Queries) TryBumpUserMonthReserved(ctx context.Context, arg TryBumpUserMonthReservedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, tryBumpUserMonthReserved, arg.AmountUsdMicros, arg.RouterUserID, arg.LimitUsdMicros)
	var router_user_id uuid.UUID
	err := row.Scan(&router_user_id)
	return router_user_id, err
}
