// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spiral_shadow_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countSpiralShadowEvents = `-- name: CountSpiralShadowEvents :one
SELECT COUNT(*)
FROM router.spiral_shadow_events
WHERE session_key = $1::bytea
  AND role        = $2::varchar
  AND reason      = $3::varchar
`

type CountSpiralShadowEventsParams struct {
	SessionKey []byte
	Role       string
	Reason     string
}

// Once-per-(session, role, reason) budget check: any prior event means this
// signal class already fired for this session and must not produce another
// row, even across replicas and in-proc cache expiry.
//
//	SELECT COUNT(*)
//	FROM router.spiral_shadow_events
//	WHERE session_key = $1::bytea
//	  AND role        = $2::varchar
//	  AND reason      = $3::varchar
func (q *Queries) CountSpiralShadowEvents(ctx context.Context, arg CountSpiralShadowEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSpiralShadowEvents, arg.SessionKey, arg.Role, arg.Reason)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSpiralShadowEvent = `-- name: InsertSpiralShadowEvent :exec
INSERT INTO router.spiral_shadow_events (
    installation_id,
    session_key,
    role,
    routed_model,
    turn_type,
    reason,
    err_streak,
    errored_results,
    tool_results,
    max_same_file_edits,
    same_file_path_hash,
    repeat_frac,
    monologue_len,
    tool_call_count,
    message_count
) VALUES (
    $1::uuid,
    $2::bytea,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::varchar,
    $7::int,
    $8::int,
    $9::int,
    $10::int,
    $11::varchar,
    $12::double precision,
    $13::int,
    $14::int,
    $15::int
)
`

type InsertSpiralShadowEventParams struct {
	InstallationID   uuid.UUID
	SessionKey       []byte
	Role             string
	RoutedModel      string
	TurnType         string
	Reason           string
	ErrStreak        int32
	ErroredResults   int32
	ToolResults      int32
	MaxSameFileEdits int32
	SameFilePathHash string
	RepeatFrac       float64
	MonologueLen     int32
	ToolCallCount    int32
	MessageCount     int32
}

// Records one shadow-mode spiral detection. Written at detection time with
// context.Background() (the request ctx may already be canceled); fire rate,
// precision, and lead time are computed offline by joining session_key
// against model_router_request_telemetry / session outcomes.
//
//	INSERT INTO router.spiral_shadow_events (
//	    installation_id,
//	    session_key,
//	    role,
//	    routed_model,
//	    turn_type,
//	    reason,
//	    err_streak,
//	    errored_results,
//	    tool_results,
//	    max_same_file_edits,
//	    same_file_path_hash,
//	    repeat_frac,
//	    monologue_len,
//	    tool_call_count,
//	    message_count
//	) VALUES (
//	    $1::uuid,
//	    $2::bytea,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::varchar,
//	    $7::int,
//	    $8::int,
//	    $9::int,
//	    $10::int,
//	    $11::varchar,
//	    $12::double precision,
//	    $13::int,
//	    $14::int,
//	    $15::int
//	)
func (q *Queries) InsertSpiralShadowEvent(ctx context.Context, arg InsertSpiralShadowEventParams) error {
	_, err := q.db.Exec(ctx, insertSpiralShadowEvent,
		arg.InstallationID,
		arg.SessionKey,
		arg.Role,
		arg.RoutedModel,
		arg.TurnType,
		arg.Reason,
		arg.ErrStreak,
		arg.ErroredResults,
		arg.ToolResults,
		arg.MaxSameFileEdits,
		arg.SameFilePathHash,
		arg.RepeatFrac,
		arg.MonologueLen,
		arg.ToolCallCount,
		arg.MessageCount,
	)
	return err
}
