// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription_credentials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscriptionCredential = `-- name: CreateSubscriptionCredential :one
INSERT INTO router.subscription_credentials (
    installation_id,
    external_id,
    user_email,
    provider,
    account_label,
    account_fingerprint,
    chatgpt_account_id,
    access_token_ciphertext,
    refresh_token_ciphertext,
    access_token_expires_at,
    created_by
)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5,
    $6::varchar,
    $7,
    $8::bytea,
    $9::bytea,
    $10,
    $11
)
RETURNING id, installation_id, external_id, user_email, provider, account_label, account_fingerprint, chatgpt_account_id, access_token_ciphertext, refresh_token_ciphertext, access_token_expires_at, last_refreshed_at, last_used_at, refresh_failed_at, created_at, updated_at, deleted_at, created_by
`

type CreateSubscriptionCredentialParams struct {
	InstallationID         uuid.UUID
	ExternalID             string
	UserEmail              string
	Provider               string
	AccountLabel           *string
	AccountFingerprint     string
	ChatgptAccountID       *string
	AccessTokenCiphertext  []byte
	RefreshTokenCiphertext []byte
	AccessTokenExpiresAt   pgtype.Timestamptz
	CreatedBy              *string
}

// Creates a new subscription credential in a user's pool. The unique index on
// (installation_id, user_email, provider, account_fingerprint) WHERE deleted_at
// IS NULL enforces one row per enrolled account; callers soft-delete by
// fingerprint before inserting to replace tokens on re-enrollment.
//
//	INSERT INTO router.subscription_credentials (
//	    installation_id,
//	    external_id,
//	    user_email,
//	    provider,
//	    account_label,
//	    account_fingerprint,
//	    chatgpt_account_id,
//	    access_token_ciphertext,
//	    refresh_token_ciphertext,
//	    access_token_expires_at,
//	    created_by
//	)
//	VALUES (
//	    $1::uuid,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::varchar,
//	    $5,
//	    $6::varchar,
//	    $7,
//	    $8::bytea,
//	    $9::bytea,
//	    $10,
//	    $11
//	)
//	RETURNING id, installation_id, external_id, user_email, provider, account_label, account_fingerprint, chatgpt_account_id, access_token_ciphertext, refresh_token_ciphertext, access_token_expires_at, last_refreshed_at, last_used_at, refresh_failed_at, created_at, updated_at, deleted_at, created_by
func (q *Queries) CreateSubscriptionCredential(ctx context.Context, arg CreateSubscriptionCredentialParams) (RouterSubscriptionCredential, error) {
	row := q.db.QueryRow(ctx, createSubscriptionCredential,
		arg.InstallationID,
		arg.ExternalID,
		arg.UserEmail,
		arg.Provider,
		arg.AccountLabel,
		arg.AccountFingerprint,
		arg.ChatgptAccountID,
		arg.AccessTokenCiphertext,
		arg.RefreshTokenCiphertext,
		arg.AccessTokenExpiresAt,
		arg.CreatedBy,
	)
	var i RouterSubscriptionCredential
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ExternalID,
		&i.UserEmail,
		&i.Provider,
		&i.AccountLabel,
		&i.AccountFingerprint,
		&i.ChatgptAccountID,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenCiphertext,
		&i.AccessTokenExpiresAt,
		&i.LastRefreshedAt,
		&i.LastUsedAt,
		&i.RefreshFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getActiveSubscriptionCredentialsForUser = `-- name: GetActiveSubscriptionCredentialsForUser :many
SELECT id, installation_id, external_id, user_email, provider, account_label, account_fingerprint, chatgpt_account_id, access_token_ciphertext, refresh_token_ciphertext, access_token_expires_at, last_refreshed_at, last_used_at, refresh_failed_at, created_at, updated_at, deleted_at, created_by
FROM router.subscription_credentials
WHERE installation_id = $1::uuid
  AND user_email = $2::varchar
  AND deleted_at IS NULL
  AND refresh_failed_at IS NULL
ORDER BY provider, created_at
`

type GetActiveSubscriptionCredentialsForUserParams struct {
	InstallationID uuid.UUID
	UserEmail      string
}

// Returns a user's usable pool for rotation, oldest-enrolled first (stable
// rotation order). Excludes credentials whose refresh terminally failed —
// those need re-enrollment before they can serve again.
//
//	SELECT id, installation_id, external_id, user_email, provider, account_label, account_fingerprint, chatgpt_account_id, access_token_ciphertext, refresh_token_ciphertext, access_token_expires_at, last_refreshed_at, last_used_at, refresh_failed_at, created_at, updated_at, deleted_at, created_by
//	FROM router.subscription_credentials
//	WHERE installation_id = $1::uuid
//	  AND user_email = $2::varchar
//	  AND deleted_at IS NULL
//	  AND refresh_failed_at IS NULL
//	ORDER BY provider, created_at
func (q *Queries) GetActiveSubscriptionCredentialsForUser(ctx context.Context, arg GetActiveSubscriptionCredentialsForUserParams) ([]RouterSubscriptionCredential, error) {
	rows, err := q.db.Query(ctx, getActiveSubscriptionCredentialsForUser, arg.InstallationID, arg.UserEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterSubscriptionCredential
	for rows.Next() {
		var i RouterSubscriptionCredential
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.ExternalID,
			&i.UserEmail,
			&i.Provider,
			&i.AccountLabel,
			&i.AccountFingerprint,
			&i.ChatgptAccountID,
			&i.AccessTokenCiphertext,
			&i.RefreshTokenCiphertext,
			&i.AccessTokenExpiresAt,
			&i.LastRefreshedAt,
			&i.LastUsedAt,
			&i.RefreshFailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionCredentialsForUser = `-- name: ListSubscriptionCredentialsForUser :many
SELECT id, installation_id, external_id, user_email, provider, account_label, account_fingerprint, chatgpt_account_id, access_token_ciphertext, refresh_token_ciphertext, access_token_expires_at, last_refreshed_at, last_used_at, refresh_failed_at, created_at, updated_at, deleted_at, created_by
FROM router.subscription_credentials
WHERE installation_id = $1::uuid
  AND user_email = $2::varchar
  AND deleted_at IS NULL
ORDER BY provider, created_at
`

type ListSubscriptionCredentialsForUserParams struct {
	InstallationID uuid.UUID
	UserEmail      string
}

// Returns every non-deleted credential for a user, including refresh-failed
// ones, for the enrollment listing endpoint.
//
//	SELECT id, installation_id, external_id, user_email, provider, account_label, account_fingerprint, chatgpt_account_id, access_token_ciphertext, refresh_token_ciphertext, access_token_expires_at, last_refreshed_at, last_used_at, refresh_failed_at, created_at, updated_at, deleted_at, created_by
//	FROM router.subscription_credentials
//	WHERE installation_id = $1::uuid
//	  AND user_email = $2::varchar
//	  AND deleted_at IS NULL
//	ORDER BY provider, created_at
func (q *Queries) ListSubscriptionCredentialsForUser(ctx context.Context, arg ListSubscriptionCredentialsForUserParams) ([]RouterSubscriptionCredential, error) {
	rows, err := q.db.Query(ctx, listSubscriptionCredentialsForUser, arg.InstallationID, arg.UserEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterSubscriptionCredential
	for rows.Next() {
		var i RouterSubscriptionCredential
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.ExternalID,
			&i.UserEmail,
			&i.Provider,
			&i.AccountLabel,
			&i.AccountFingerprint,
			&i.ChatgptAccountID,
			&i.AccessTokenCiphertext,
			&i.RefreshTokenCiphertext,
			&i.AccessTokenExpiresAt,
			&i.LastRefreshedAt,
			&i.LastUsedAt,
			&i.RefreshFailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionCredentialRefreshFailed = `-- name: MarkSubscriptionCredentialRefreshFailed :exec
UPDATE router.subscription_credentials
SET refresh_failed_at = NOW(), updated_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Marks a credential's refresh as terminally failed (4xx from the token
// endpoint); the pool skips it until the user re-enrolls.
//
//	UPDATE router.subscription_credentials
//	SET refresh_failed_at = NOW(), updated_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) MarkSubscriptionCredentialRefreshFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSubscriptionCredentialRefreshFailed, id)
	return err
}

const markSubscriptionCredentialUsed = `-- name: MarkSubscriptionCredentialUsed :exec
UPDATE router.subscription_credentials
SET last_used_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

// Fire-and-forget update after a pooled credential serves a turn.
//
//	UPDATE router.subscription_credentials
//	SET last_used_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
func (q *Queries) MarkSubscriptionCredentialUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSubscriptionCredentialUsed, id)
	return err
}

const softDeleteSubscriptionCredential = `-- name: SoftDeleteSubscriptionCredential :execrows
UPDATE router.subscription_credentials
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1::uuid
  AND installation_id = $2::uuid
  AND user_email = $3::varchar
  AND deleted_at IS NULL
`

type SoftDeleteSubscriptionCredentialParams struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	UserEmail      string
}

// Soft-deletes one credential. Cross-tenant safe via installation_id and
// user_email predicates; a foreign id matches zero rows.
//
//	UPDATE router.subscription_credentials
//	SET deleted_at = NOW(), updated_at = NOW()
//	WHERE id = $1::uuid
//	  AND installation_id = $2::uuid
//	  AND user_email = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteSubscriptionCredential(ctx context.Context, arg SoftDeleteSubscriptionCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSubscriptionCredential, arg.ID, arg.InstallationID, arg.UserEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteSubscriptionCredentialByFingerprint = `-- name: SoftDeleteSubscriptionCredentialByFingerprint :exec
UPDATE router.subscription_credentials
SET deleted_at = NOW(), updated_at = NOW()
WHERE installation_id = $1::uuid
  AND user_email = $2::varchar
  AND provider = $3::varchar
  AND account_fingerprint = $4::varchar
  AND deleted_at IS NULL
`

type SoftDeleteSubscriptionCredentialByFingerprintParams struct {
	InstallationID     uuid.UUID
	UserEmail          string
	Provider           string
	AccountFingerprint string
}

// Soft-deletes the existing row for an enrolled account before re-inserting
// fresh tokens (replace-on-re-enrollment).
//
//	UPDATE router.subscription_credentials
//	SET deleted_at = NOW(), updated_at = NOW()
//	WHERE installation_id = $1::uuid
//	  AND user_email = $2::varchar
//	  AND provider = $3::varchar
//	  AND account_fingerprint = $4::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteSubscriptionCredentialByFingerprint(ctx context.Context, arg SoftDeleteSubscriptionCredentialByFingerprintParams) error {
	_, err := q.db.Exec(ctx, softDeleteSubscriptionCredentialByFingerprint,
		arg.InstallationID,
		arg.UserEmail,
		arg.Provider,
		arg.AccountFingerprint,
	)
	return err
}

const updateSubscriptionCredentialTokens = `-- name: UpdateSubscriptionCredentialTokens :exec
UPDATE router.subscription_credentials
SET access_token_ciphertext = $1::bytea,
    refresh_token_ciphertext = $2::bytea,
    access_token_expires_at = $3,
    last_refreshed_at = NOW(),
    refresh_failed_at = NULL,
    updated_at = NOW()
WHERE id = $4::uuid
  AND deleted_at IS NULL
`

type UpdateSubscriptionCredentialTokensParams struct {
	AccessTokenCiphertext  []byte
	RefreshTokenCiphertext []byte
	AccessTokenExpiresAt   pgtype.Timestamptz
	ID                     uuid.UUID
}

// Persists rotated tokens after a successful refresh and clears any earlier
// terminal-failure mark.
//
//	UPDATE router.subscription_credentials
//	SET access_token_ciphertext = $1::bytea,
//	    refresh_token_ciphertext = $2::bytea,
//	    access_token_expires_at = $3,
//	    last_refreshed_at = NOW(),
//	    refresh_failed_at = NULL,
//	    updated_at = NOW()
//	WHERE id = $4::uuid
//	  AND deleted_at IS NULL
func (q *Queries) UpdateSubscriptionCredentialTokens(ctx context.Context, arg UpdateSubscriptionCredentialTokensParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionCredentialTokens,
		arg.AccessTokenCiphertext,
		arg.RefreshTokenCiphertext,
		arg.AccessTokenExpiresAt,
		arg.ID,
	)
	return err
}
